### ISSUE TITLE
Arc 4 or Console Arcs?

### ISSUE THREAD

**Issue by OcimaNayr** [07th-mod/higurashi-console-arcs#1]
Is this suppose to make Himatsubishi unplayable or is that a glitch? I thought the point was you could choose which one to play, but Someutsushi replaced Himatsubishi completely.

**Comment by enumag** [comment]
That's right, the patch replaces Himatsubushi with Someutsushi. If you want to be able to have both Himatsubushi and Someutsushi at the same time you'll need to have two instances of Himatsubushi on your PC.

There is unfortunately still the disadvantage of the two games sharing one save directory.
