### ISSUE TITLE
Chapter select screen options not centered

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#10]
@P-Chang, @enumag 

The options in the selection dialog are shifted over to the right.  It's called with the Select() function.  This affects both the chapter select screen and the View TIPS screen in the console arcs.  There's also one choice in the tips for Hima that probably has the same issue.  If I had to guess, I'd say this is a consequence of the change to shift the menu buttons to the far right corner.

![image](https://user-images.githubusercontent.com/20390474/34323121-edcf1c38-e808-11e7-88c4-d95a987224ac.png)

**Comment by P-Chang** [comment]
Reason is probably we moved GUI pos. triangle and square button had same problem in the past, I'll look over this.

But... method that control choice button are disliked from decompiler, so it take a some time.
And one more problem of it, choice button were not designed for over 4( or 5) buttons, so we can't use over 4 button now.

**Comment by DoctorDiablo** [comment]
If you can get system to handle more than 4 buttons, that would be great.  I'm still hoping to eventually have all 10 arcs in here, but that'll take forever so no rush.  For now, I can always make the last choice a "next" button that displays a second set of options.

**Comment by enumag** [comment]
@DoctorDiablo Is this solved? I mean you have some newer screenshots in https://github.com/07th-mod/higurashi-dlls/issues/13 where this bug does not appear.

**Comment by DoctorDiablo** [comment]
Nope, this one is still busted.  That screen was taken using an outdated version of the dll.

I think I've got an idea how to fix this though.  I'll see what I can do.

**Comment by DoctorDiablo** [comment]
Fixed in v4.0.0
