### ISSUE TITLE
Sprite Overhaul

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#11]
@Grelo , @irlPM, @enumag 

There are a couple enhancements we can make to the sprites in the console arcs release:

1. All sprites are currently in 720p.  We can replace these with the 1440 ones or make 1080p ones, I'd be fine either way.
2. The weather sprites are at a nonstandard resolution, 1280x960.  This was the only way I could get them to display without aliasing issues, but it would be better to make everything the same dimensions to be consistent.
3. The weather sprites are specified with _night and _sunset and the end of the filenames, but we should move those to separate night and sunset folders to be consistent with the way we specify these in the other arcs.  This will also require script changes to point to the new paths.
4. There are currently no MangaGamer sprites for any of the console arcs.  Almost all the characters in the 2 finished arcs are original to the PS3 version, but there are some sprites for Ooishi, Rika, and Mion that we could add.  These would also need weather variants.

**Comment by irlPM** [comment]
I already made all the Sprites with the 1440p resolution including the weather variations but it seems that the 1440p is giving problems to lipsync so I don't know if we should use them.

**Comment by DoctorDiablo** [comment]
Gotcha.  Well, I guess we should let the rest of the team figure out lipsync and just go along with whatever they decide.

**Comment by enumag** [comment]
Let me ping @P-Chang here to get some info about the issue with lip-sync and 1440p.

**Comment by P-Chang** [comment]
Basically, new way could handle 1440p one. but 1080p one have more better performance.
1440p one have terrible performance because game was designed as every time load sprites from drive.

New way store 3 sprites in VRAM with lipsync.
But I didn't concern 0.5GB or 1GB VRAM user.

**Comment by enumag** [comment]
That's a tough call to make. My own PC should be able to run 1440p no problem (GTX 1060) and it would be better for me since I have 1440p monitor but I'm not sure what setup are other people using. Maybe we should stick to 1080p to be safe? cc @ItaloKnox

**Comment by ItaloKnox** [comment]
I'm running a GTX 970 OC'd so I should be around the same specs of a 1060 6gb. We have the full graphics set already upscaled to 1440p so it's only a matter of testing. For me, we could go with 1440p, but I'm worried about the users running low-spec machines. We shouldn't make the game too hard to run. Also, stuttering is a no go for me, so if we want to go with 1440p, I would prefer the stuttering to not be there.

**Comment by enumag** [comment]
Alright then. @P-Chang Do you think you could somehow further improve the performance of 1440p? If not then let's stick with 1080p for now. Maybe we could later make an alternate graphics patch for high performance users or something.

Also can we somehow continue here for the console arcs or should we make the new graphics patches for the main arcs first? I'm not sure if these things depend on each other or not.

**Comment by DoctorDiablo** [comment]
My monitor is 1080p so anything beyond that doesn't help me much.

It would be nice to put together separate packages for 1080p and 1440p.  I'd say the installer should give users the 1080p ones and enthusiasts with beefier computers can manually install the 1440p ones.  Shouldn't be too hard to set up if we already have all the sprites.

Definitely focus on getting things done in the main arcs first, there are far more users on those.

**Comment by P-Chang** [comment]
Decompiler say one method is broken, but you can test with this.
http://www.mediafire.com/file/3uvmm462bv25oln/chapter1_lip_test_12.24.rar

I deleted old simple routine lipsync in this test so if you don't have voice analyzed file, lipsync never start.

@enumag 
Stuffer is related in file reading speed, I can't fix it.

**Comment by enumag** [comment]
@P-Chang Is it possible to pre-load more files to memory? I mean even the worst graphics cards have like 512MB VRAM which should still easily load dozens of 1440p images. Of course it might not be possible with the engine. By the way are you using SSD or HDD? I have a new super-fast SSD drive connected to M2 slot instead of normal sata. It might work alright on such high-end setup. I'll have to try it later.

**Comment by P-Chang** [comment]
SSD SATA 600MB/s

Pre-load is probably possible. but game doesn't have loading time like we always see in another game.
It means I need put it in Launch or MainMenu or Hotkey, I can't think it is good.

And I can't know how game use VRAM in low end. probably engine optimize it.
but in my rig, VRAM usage is over 700MB in Launch.

Personally it kindness for drive, if I made it for only me, i implement it. but I think always keeping texture  cause incomprehensible issue.

I'm really interested in how M2 slot SSD is faster :D

**Comment by ItaloKnox** [comment]
Is it possible to make the game load in vram only the sprites used in the script you are currently playing? I don't think it's a big problem to load it while loading a save or starting a new game. We have a break between the chapters, so unloading the sprites and loading the next sprites would also work.

**Comment by enumag** [comment]
@ItaloKnox My thoughts exactly. :-)

@P-Chang Well Sata III has limit 6Gb/s which equals 750MB/s - it can't go any faster than that because the slot can't handle it. 600MB/s is pretty close to the limit so very fast for a sata drive.

M.2 however can go way beyond that. According to specs my M.2 SSD (Samsung 960 EVO 500GB) has 3200MB/s for reading and 1800MB/s for writing. Might be enough for 1440p lipsync - I'll be quite disappointed of my SSD if the game stutters.

**Comment by irlPM** [comment]
If anyone wants to check here is the link for all 1440p Sprites with the weather variations: https://mega.nz/#!v80FAbxS!BQdOrCTbR98Yf1FTM-DXiZUEcAj0l0evSP5Ve3wRplg

**Comment by irlPM** [comment]
Just PM me in discord if you need a paid mega account because of the download limit meme

**Comment by ItaloKnox** [comment]
Here's a mirror on my server: http://ichigohi.me/root/Weather%20Sprites.zip

I'll leave it up for a week or so, I'll put it on the server later.

**Comment by P-Chang** [comment]
It will come after I completely understand compiler and savedata control and fix scope system bug.

For now. I can do it with only regex. I won't do like that.

**Comment by Grelo** [comment]
Is there a difference?
![aka_def_0](https://user-images.githubusercontent.com/22790067/34365945-018332ca-ea96-11e7-94f3-20b4c5e83567.png)
![aka_def_0](https://user-images.githubusercontent.com/22790067/34365947-0558808a-ea96-11e7-8857-c69aed300e0c.png)

**Comment by enumag** [comment]
@Grelo As fas as I can tell they look identical.

**Comment by enumag** [comment]
@Grelo Oh I see the difference now. The top one is better.

**Comment by Grelo** [comment]
and these?
![aka_def_0](https://user-images.githubusercontent.com/22790067/34366076-54ad0b00-ea97-11e7-9378-05b5bba1cfa3.png)
![aka_def_0](https://user-images.githubusercontent.com/22790067/34366078-592baf60-ea97-11e7-81a1-3d8b75c97ef5.png)

**Comment by Grelo** [comment]
Ok thanks.

**Comment by enumag** [comment]
The second set seems to be the same thing in 1440p - maybe the difference is more subtle because it was harder to see. The top one is again bette in my opinion but I would never notice any difference without looking for it.

**Comment by DoctorDiablo** [comment]
I had to zoom in to see the difference.  Top one looks slightly better, it has smoother lines.  But really, they're essentially the same to me.
