### ISSUE TITLE
Extract asset from Sui

### ISSUE THREAD

**Issue by Nozoki17** [07th-mod/higurashi-console-arcs#12]
Hello! I'm pretty sure it's not the right place, but since it's about console arcs, I wanted to atleast be somewhat related. I recently got access to Sui, and I wanted to toy around with the assets of Yoigoshi-hen, but I have absolutely no idea how to get in the "Data.rom"

**Comment by enumag** [comment]
@Nozoki17 Try contacting Inochi-PM on our discord. He said he has the files from Sui data.rom (although he didn't decode it himself).

@ItaloKnox It might be nice to get our hands on those files as well and upload them on your server or our resoursec repo.

**Comment by enumag** [comment]
Oh wait he is her on GH as well. Ping @InochiPM!

**Comment by DoctorDiablo** [comment]
@Nozoki17 We have most of the assets from the Sui available in our resources repository: https://github.com/07th-mod/resources The graphics, audio, and script are all there, so you might not need to extract anything yourself.  Of course, if you do, feel free to post it here.  Might help us out too.

**Comment by ItaloKnox** [comment]
@enumag Actually I was in contact with someone over email because they asked about it. Not sure if it was OP or someone else, but I asked to keep me updated. Supposing the files come up somewhere, I can easily use my server do pull them and have them available anytime.

**Comment by InochiPM** [comment]
@Nozoki17 I had someone build me a BMS script that gets all of the files from sui, the issue i have is that the file types they come out to be i have no clue how to extract them. I have all of the files extracted on my PC i just have no clue how to extract them all. ill post the script if needed!
