### ISSUE TITLE
Prologue Translation

### ISSUE THREAD

**Issue by InochiPM** [07th-mod/higurashi-console-arcs#13]
So after spending a long ass time yesterday transcribing the prologue onto a text file, I got it fully translated into english but I dont know how to make a script for the game, and i dont wanna mess something up hah! 
Heres my translated version, and it may need some proofreading from the original Japanese since my Japanese is a bit rusty. In my script i have the Bg's marked down where they appear, as-well as what BGM plays when, i have the Bg's in a zip folder since the one used for the ceiling of the room doesn't have the black halo. 
[Prologue_EN.txt](https://github.com/07th-mod/higurashi-console-arcs/files/1657919/Prologue_EN.txt)

BF file.
[BG.zip](https://github.com/07th-mod/higurashi-console-arcs/files/1657927/BG.zip)

[Script_SUI-.txt](https://github.com/07th-mod/higurashi-console-arcs/files/1657923/Script_SUI-.txt)
Here's the original script from the sui script for reference.

**Comment by InochiPM** [comment]
I'm also posting the text file here so i can edit it if needed. *Im also adding what transitions go where. 
Remembrance/Prologue
BGM - Silent with crickets, i don't the name of the bgm sorry. 

bg_black

.......I can hear the sound of snoring coming from somewhere.

Noticing it was my own, I slowly opened my eyes to a slightly blurred sight.

Mask - c.png
bg_223.png

Ōishi - "..........."

Reflected in my field of view was a thin dirty ceiling that shone with bright fluorescent lights. 

It seems I had nodded off, In earnest I planned to lie down on the sofa in the break room for a bit, but its seems to have gone unnoticed.

Having fallen asleep in a strange position, there is a slight dull pain around my shoulders and forehead.... Well I'll leave it alone for now. In a while the blood circulation should return back to normal.

Ōishi -「...Oof...」

Mask - C.png inverted to white i think 

BGM - start (夜鈴の調ベ)
bg_112.png

Slowly moving my upper body, I place my hand on the side of my neck, rubbing and kneading along the scruffy sides. A long yawn leaks from my mouth.

The hour hand of the large clock crossed over the top. An ashtray sat on the desk with a single cigarette, burned all the way to the butt.

......I don't have any memory of smoking before I nodded off, then again I could have wanted a smoke. I could of dropped it on the sofa, being so careless I could have started a fire.  

Ōishi -「.....Dangerous, very dangerous」

With a bitter smile, I stand up ashtray in hand and I drop it into a cigarette bin in the corner of the room.

In the bin, a myriad of cigarette butts and muddy water with an ochre color are packed together and piled up. Not to mention the foul odor emanating from them, causing me to frown.

......Thanks to the putrid smell, the feeling of sleep has all but gone away. 

Ōishi -「Sooner or later ill quit smoking」

Starting tomorrow - No, Looking at my watch the date had already changed making it already tomorrow. So starting today.

From now on, in spite of my desire to I need to stay awake all night, to eliminate the chance of loosing concentration and loosing my cool. 

Rather, anything is better than spending all of my time being "dazed" without thinking. It would be much better for my health if I just stopped. 

......Nevertheless, because of those ingrained habits I don't think I have the confidence to be able to quit. I hope there is an alternative to Sleeping, Eating and Hitting that are fun.  

Ōishi -「Other than non-criminal, how do I spend my day....
Because I'm not cut out for farm work......Hahahahah」

Imagining myself working on a farm in the soil, it makes me laugh a bit.

Its a very unrealistic story, But I haven't had the time to look into the new place since my departure happening next week.

The memorable scenery was supposed to be more than the just city of Okinomiya......Its a long time now since I last visited my mother, i can't even think about it now.

It was written in a letter that as a part of the construction plans to build a large scale airport, traffic would become more convenient. Well well well.

Ōishi -「Well, that would be nice....
Even though my life won't be ending any time soon, its a fun thing to know after you go.」

Besides, ill be taking care of my elderly mother from here on out. That alone should be a good time killer.

Having a strong and healthy body, For a long time my parents left me alone to do whatever I wanted. And if we didn't imitate filial piety​, it is said that a divine punishment would be bestowed upon us......

Ōishi -「Divine punishment......or」

Mask - Fade to black.
bg_black

After ruminating over those words, I pick up one of the thick files that were placed along my desk. I stare at the name thats written on the cover. 

[Hinamizawa Serial Deaths & Related Missing Cases] -.

Truly, if there were something called divine punishment, it wouldn’t of been like this. At least, to scale its easier to measure it to human knowledge than to  a mystery. 

Mask - Fade in from black.
BGM - start (Confession)
bg_112.png

Ōishi - 「Hinamizawa Vilage......」

Its official name, Shishibone City - Hinamizawa district.

In this village with a population of around 2000 people, the mayor and other authorities hardly count as such, The true powers are what they call “The Three Great Houses” they dominate over all other and are as old as the land itself. 

And the practice of their private faith in an indigenous god named “Oyashiro-sama” was passed down among the local residents for generations…. As well as a “Curse” onto those who do not believe, becoming a more common occurrence. 

Ōishi - 「......」

However, the village nowadays being "Nonexistent", Leaving those who remain scattered around in various places. 

That was in the beginning, With every case summarized in this file......
Mask - x.png then fade.
sui_title02.png

ーENDー

**Comment by DoctorDiablo** [comment]
[prologue.txt](https://github.com/07th-mod/higurashi-console-arcs/files/1670188/prologue.txt)

I put together a script file that includes your translation and all the appropriate effects.  It should work in both English and Japanese.  I used the filenames from the ps3 version to keep it consistent with the console arcs release, so you'll have to rename your BGs and find the appropriate music/voice files.  I haven't taken the time to review your translation yet, but I'll try to do that in the future.

Sorry for the slow reply, I've been a little busy lately.  If you're interested in doing the scripting work yourself, it's actually pretty easy.  You just need to open the files in a text editor (I use Notepad++) and add the appropriate functions at the appropriate points in the script.  I've got a reference file with all the functions I regularly use that you can take a look at, and you can see where I put them in the prologue to figure out how they're used.

[scripting cheat sheet.txt](https://github.com/07th-mod/higurashi-console-arcs/files/1670189/scripting.cheat.sheet.txt)

**Comment by InochiPM** [comment]
oh cool! thats fine it took me a few days to get the translation correct anyway and some parts need grammar check aswell. As for the scripting, i would like to but i personally dont have the time to try to do it and learn it myself since im still in college with tight deadlines ^^;; so i can wait for someone else to do it, who has time its no big deal

**Comment by DoctorDiablo** [comment]
Included in v5.0.0 release.
