### ISSUE TITLE
Kageboushi not playable on Linux

### ISSUE THREAD

**Issue by Admiral124** [07th-mod/higurashi-console-arcs#17]
In multiple specific points, the game seems to lock up for no reason. The first time it occurs is in the first scene when Ooishi says: 

> Well, you usually hide it really well. There's just a little bit that gave it away. Na ha ha ha.

You can get a little further by saving just before this line and reloading, but then it happens again a little further along while they are talking about Tomoe's sister. Further, the only sprite that seems to load is Ooishi. Tomoe does not appear at all.

**Comment by DoctorDiablo** [comment]
This should be fixed in the new [3.0.0 release](https://github.com/07th-mod/higurashi-console-arcs/releases/tag/v3.0.0)

Anyone willing to test it on Linux?

**Comment by Petsnew** [comment]
3.0.0 is working fine on Arch Linux

**Comment by enumag** [comment]
Closing then. Thank you!
