### ISSUE TITLE
Translation issues: Miotsu

### ISSUE THREAD

**Issue by Mikulovers** [07th-mod/higurashi-console-arcs#173]
Starting with 1 but will post more if I find.
![bild](https://user-images.githubusercontent.com/39219285/89695720-472ea000-d915-11ea-947b-6c48ee199f91.png)
![bild](https://user-images.githubusercontent.com/39219285/89695876-e2c01080-d915-11ea-8428-0c05ba5dede8.png)

"A drunk old man cant take me home" it says but its written in japanese like "Noone else but me can take the drunk old man home" or something like that. If I misread the meaning I apologize.

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89696338-befdca00-d917-11ea-9d98-64a2c6615a77.png)
![bild](https://user-images.githubusercontent.com/39219285/89696347-c91fc880-d917-11ea-94a1-28801bd4b356.png)

Keiichi's word in this context mean something in the lines of "Isn't that obvious?"

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89719722-9cc58400-d9cb-11ea-8039-51b414581d5a.png)
![bild](https://user-images.githubusercontent.com/39219285/89719726-a64eec00-d9cb-11ea-9721-e842623366b6.png)
The principal words mean something along the lines of "Just overlook it/Give her a break"

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89719784-663c3900-d9cc-11ea-995d-56cfb20dd79e.png)"

"I knew you could do it" -> something along the lines of  "I was sure/certain you would dodge"
(Posting only the english pic because lazy. If this TL was your localization and not a mistranslation its my mistake.)

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89720153-86212c00-d9cf-11ea-8561-4f8f93dd2ba5.png)
![bild](https://user-images.githubusercontent.com/39219285/89720164-a9e47200-d9cf-11ea-9cd0-c5a35e306b75.png)

I am not able to give a proper or close TL of what this should be, but she is not talking about Teppei in a good light in the 2nd part Im pretty sure.

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89720411-18c2ca80-d9d2-11ea-9f6f-992cea386d9e.png)
![bild](https://user-images.githubusercontent.com/39219285/89720414-211b0580-d9d2-11ea-87ee-d67443147e1d.png)

Current -> "Shion sure called/invited us to a bad place"

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89721012-b6b99380-d9d8-11ea-940f-adb6c28293cb.png)
![bild](https://user-images.githubusercontent.com/39219285/89721017-c1742880-d9d8-11ea-8206-e9ba190040b2.png)

Im pretty sure hes talking in third person about someone else that is not himself?

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89740184-deffcb80-da86-11ea-9a8c-8327b41dad7a.png)
![bild](https://user-images.githubusercontent.com/39219285/89740198-f17a0500-da86-11ea-80b9-a81d63b23d49.png)

Irie is saying something along the lines of "Just the thought makes you shiver", not specifically mentioning Satoko

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89743728-2b0e3880-daa6-11ea-894f-068eb9b005f4.png)

This and some lines at the bar with Akasaka+Oishi+Forensic+Kuma could be fixed by checking the exact same lines in Matsuribayashi steam translations.

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89887852-50e32c80-dbcf-11ea-9e2b-36dc10dfae2a.png)

Compare to same line TL in Matsuribayashi

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89892863-9c99d400-dbd7-11ea-80f4-40281b36438a.png)

-> "I still havent accepted him" (shes referring to Keiichi not her own romance)

**Comment by Mikulovers** [comment]
![bild](https://user-images.githubusercontent.com/39219285/89954691-de576880-dc31-11ea-864f-e846e0f790d7.png)

Refer to my 2nd comment

**Comment by Mikulovers** [comment]
There were a few I missed for this chapter as I was too absorbed into the action so I did not take a picture of those, but as I have finished reading this chapter I will now close this.

**Comment by Mikulovers** [comment]
I have finished reading this chapter now so when you have found and fixed the TL issues I have pointed out feel free to close this issue.

**Comment by DoctorDiablo** [comment]
Thanks for helping out!  Just pushed a fix for all of these except for the ones about copying the TL from Matsuri.  I'm going to open a separate issue to keep track of those so I can try to locate any other lines line that.
