### ISSUE TITLE
Certain Japanese characters display as red X

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#2]
The following kanji don't display correctly in the engine: 訊,髪,梳,遜,襖,滔,憬,皺,躓,逡,賦,耗,侘,竦,詈,悄,芻,饐,腿,窄,掠 and instead show up as a red X.  The English version is the main focus of this mod, but it would be nice to have the Japanese option 100% working.

I tried changing the font, but it didn't make a difference.  I also tried installing the patch on top of Meakashi in case MG made improvements to the engine since then, but that didn't help either.

I haven't tried changing my locale to Japanese yet, but I don't think that will fix it because the characters are Unicode.

I really don't want to do this, but this could potentially be fixed by changing the Japanese text to write out these words in hiragana, or to use different kanji with the same meaning (聞く in place of 訊く) but I'm not comfortable enough in Japanese to be doing that.

**Comment by enumag** [comment]
Maybe we should report this as a bug to MG?

**Comment by DoctorDiablo** [comment]
Good call.  I just contacted MG support, so maybe they'll be able to help.

**Comment by DoctorDiablo** [comment]
Mangagamer just got back to me.  Looks like they're unable to do anything about it.

> Hello again.
>We do apologize, but we just wanted to contact you again to let you know that we won't be able to provide any support for mods of our release of the Higurashi series. 
>Please do let us know if we can do anything else for you, and we hope you have a great day.

**Comment by enumag** [comment]
Yeah I got the same response today regarding a different issue with the engine.

**Comment by idealpersona** [comment]
@DoctorDiablo is any of this information helpful? Would it be possible for us to generate a new font atlas as in the the third link below?

http://digitalnativestudios.com/forum/index.php?topic=262.0
http://digitalnativestudios.com/forum/index.php?topic=122.0
https://www.youtube.com/watch?time_continue=25&v=7gifMzbOyG8

**Comment by enumag** [comment]
Is the generated .asset file similar to the sharedassets0.assets file that is in the game? If so, maybe we could hack the DLL to load font from different file than sharedassets0.assets and use the generated one directly.

**Comment by DoctorDiablo** [comment]
@enumag That sounds possible.  It's the same kind of asset file, that's why UABE is able to read it.

Gonna have to do some research on how the dll loads data from these assets.

**Comment by enumag** [comment]
It would be slightly more complicated because each font would be in a separate file which is not the case now. But it should be possible to implement in my opinion. WDYT @idealpersona?

**Comment by enumag** [comment]
@tellowkrinkle You seem quite proficient with unity assets, maybe you could try to help us here? The goal is to replace the font atlas in the assets to fix missing japanese Kanji characters. DoctorDiablo was able to generate a new atlas using TextMesh Pro but was unable to put it into the assets.

@DoctorDiablo Can you post the font atlas you got from TextMesh Pro?

**Comment by tellowkrinkle** [comment]
I would guess it's this MonoBehavior file that actually does the mapping, the Material files are too small: 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/3315070/44560993-00d7da80-a718-11e8-99a0-8d908c3c9825.png">

**Comment by DoctorDiablo** [comment]
Here's the font atlas I generated from TMP: [msgothic_0.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2320267/msgothic_0.zip)

Not sure what a MonoBehavior file is, but my generated asset file didn't include one.  There are also some parameters we can set at generation like the rendering style and the amount of padding between characters.  If we can actually get this loaded in-game, we might want to tweak those to make it look better.

**Comment by tellowkrinkle** [comment]
First of all, the `.asset` file in the zip is a normal unity asset bundle and the three files can be extracted from it using UABE. 
It looks like the main issue is that the version of TMP that you're using is newer than the one used in the game so it stores a different set of fields.  Manually rearranging the entire file appears to make it readable, I can try to make a script for it later.  The Material file is not needed (and broke the game when I tried to use it, I probably didn't fix it properly).  The fixed font data was a little glitchy (you can see the other characters bleeding over into the used ones), but I noticed some of your export settings were different from the originals, could you see what happens if you use these settings (some of them are probably calculated from others, try to copy them as well as you can) 
```
PointSize 22
Padding 0
LineHeight 22
Baseline 0
Ascender 18.90625
Descender -3.09375
CenterLine 0
SuperscriptOffset 18.90625
SubscriptOffset -2.234375
SubSize 0.5
Underline -2.234375
UnderlineThickness 1.6328125
TabWidth 110
CharacterCount 3802
AtlasWidth 2048
AtlasHeight 2048
```
Fixed font file:
[FontData.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2320402/FontData.zip)
Screenshot:
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/3315070/44615843-39a3ac80-a809-11e8-9d27-fb8210486bdb.png">

**Comment by enumag** [comment]
Wow you actually got it to work? That's a big news!

**Comment by tellowkrinkle** [comment]
I think the most likely thing to fix the glitchiness is going to be to use a point size of 22 instead of 69

**Comment by DoctorDiablo** [comment]
Awesome, this is looking great.  I generated another asset with the parameters set closer to those [msgothic_0_size22.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2320736/msgothic_0_size22.zip)

These are the options TMP allows me to set during generation:
![image](https://user-images.githubusercontent.com/20390474/44618167-c157de00-a83e-11e8-9297-89521d2d7edf.png)

There's still a lot of space left in the atlas image, and it has 500 fewer characters than the old one.  I feel like it might be smart to add additional characters to the list just to future-proof it.  Is it possible to generate a list of characters in the original atlas?  Maybe we can combine them.

Also, I believe the _0 font is the regular in-game font and the _2 one is used in the backlog.  Can you tell if there's any difference between them?  Can we use the same atlas for both?

**Comment by tellowkrinkle** [comment]
Hmm the padding recorded in the file must always be 0 even though they obviously didn't use 0 padding for theirs.  Could you try one with a padding of 10 and one with a padding of 12?

I did however figure out why the font was glitching out, there are font-specific values in the Material that got lost when I didn't transfer the Material over.  Copying them onto the Material fixes it.  We may, however, want to attempt to copy some of them to avoid having our font look different from the original (especially outline settings)

Current screenshot:
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/3315070/44632740-8d1b1500-a945-11e8-9284-64d4155d249d.png">
Here's the settings that didn't match:
```
_FaceDilate was 0.1 ours was 0
_GradientScale was 7 ours was 6
_OutlineWidth was 0.1 ours was 0
_ScaleRatioA: was 0.85714287 ours was 1.0
_ScaleRatioB: was 0.75 ours was 1.0
_ScaleRatioC: was 0.3742982 ours was 1.0
_UnderlayDilate: 0.061 ours was 0
_UnderlayOffsetX: 1.0 ours was 0
_UnderlayOffsetY: -1.0 ours was 0
_UnderlaySoftness: 1.0 ours was 0
```
I'm not sure what the ScaleRatios were (fixing them didn't seem to do anything).  The Underlay corresponded with the character shadow (I'm guessing it was originally a shadow that was 1 pixel to the lower right, the dilate affects how blurry it is).  I would guess the FaceDilate slightly blurs the characters themselves, not sure what GradientScale does, and OutlineWidth corresponded to the outline.

**Comment by tellowkrinkle** [comment]
Ahh I just found [http://digitalnativestudios.com/forum/index.php?topic=890.0](http://digitalnativestudios.com/forum/index.php?topic=890.0)
So yeah we should just increase the padding
http://digitalnativestudios.com/forum/index.php?topic=890.0

**Comment by tellowkrinkle** [comment]
Alright the game files use padding 6.

Here's the current font's character list: [characterList.txt](https://github.com/07th-mod/higurashi-console-arcs/files/2321962/characterList.txt) and here's that combined with our character list: [combinedCharacterList.txt](https://github.com/07th-mod/higurashi-console-arcs/files/2321961/combinedCharacterList.txt)

**Comment by tellowkrinkle** [comment]
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/3315070/44636084-34607200-a96f-11e8-84ab-9a95c6c3bf69.png">

[msgothic_0_padding6_out.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2322116/msgothic_0_padding6_out.zip)

**Comment by DoctorDiablo** [comment]
I imported those into sharedassets0 and gave it a try.  It fixed all the kanji that used to show as red Xs in the main script, but I did still run into one of them here.  I guess my character list is missing the stuff that comes from the in-game UI.  Not sure how many other cases like this there might be.

![image](https://user-images.githubusercontent.com/20390474/44757652-21c87300-aafe-11e8-8046-06e64713612b.png)

So, I tried generating one more one atlas based on your combined character list.  Unfortunately, it couldn't fit them all in with the same parameters.  I tried tweaking the resolution, render mode, and packing method, but it always stopped at 3716.  Maybe 3716 is a hard limit on the number of characters.

![image](https://user-images.githubusercontent.com/20390474/44757913-951eb480-aaff-11e8-8ee8-5158683ec20a.png)

**Comment by tellowkrinkle** [comment]
Hmm... there's a bunch of Cyrillic and accented characters near the beginning of the original set, maybe try cutting those?

**Comment by tellowkrinkle** [comment]
[combinedCharacterList.txt](https://github.com/07th-mod/higurashi-console-arcs/files/2333110/combinedCharacterList.txt)
Here's the list with the Cyrillic and accented characters removed, leaving 3712 characters

**Comment by DoctorDiablo** [comment]
Ok, I think @tellowkrinkle and I got this all working.  Here's the latest atlas file: [msgothic_0_combined_fixed.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2342457/msgothic_0_combined_fixed.zip)

There's one problem I need to fix in the scripts though.  As a stopgap to help the original red X problem, I replaced the kanji hyphen `―` with em-dash `—` in all of the scripts.  But the em-dash renders as an X in this character set, so I need to do a quick find/replace to put the original hyphen back.  I'll have that done today

We also need to work out of we're going to maintain this change in the asset file.  Right now Himatsubushi and Console Arcs use the same asset file.  We can either apply this change on top of Hima (and hope it doesn't break anything) or we can make a separate asset file just for console arcs (and have one more thing to maintain).  I think it's best to use the same file for both, but we need to do some testing to make sure that doesn't cause any issues.

**Comment by enumag** [comment]
Actually we should try to replace the font in all arcs in my opinion. Do you think it would cause any problems? We have the character set as text file so we could write a script to check if any arc is using any missing characters.

**Comment by enumag** [comment]
Ok, I'll write it.

**Comment by DoctorDiablo** [comment]
Use this character list for your testing.  These are the 3716 that were successfully imported into the atlas.

[combinedCharacterList.txt](https://github.com/07th-mod/higurashi-console-arcs/files/2342817/combinedCharacterList.txt)

**Comment by enumag** [comment]
Ok, I have the tool, here are the results:

Meakashi:

```
Missing character: 鉤
Missing character: 〜
Missing character: 窺
Missing character: −
```

Tsumihoroboshi:

```
Missing character: 鋸
Missing character: 賎
Missing character: 〜
```

Question arcs were only missing `〜` and `−`.

The dash is most likely what you mentioned above. Can you fix the other characters?

**Comment by DoctorDiablo** [comment]
TMP failed to insert `〜` and `−` but I was able to add the other kanji.  We can probably resolve that by replacing them with `～` and `－` which are in the character set.

Here's the new character list with 3720 characters: [combinedCharacterList_3720.txt](https://github.com/07th-mod/higurashi-console-arcs/files/2343460/combinedCharacterList_3720.txt)
 
And here's the generated atlas file: [msgothic_0_3720.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2343461/msgothic_0_3720.zip)

**Comment by enumag** [comment]
Ok, thanks. Now how do I get the font into the `sharedassets0.asset` file? @tellowkrinkle?

**Comment by tellowkrinkle** [comment]
[msgothic_0_combined_fixed.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2344521/msgothic_0_combined_fixed.zip)
I still haven't made a converter script since I thought we wouldn't need to do this too many times
Here's a full atlas of 4152 characters that I made using a copy of `msgothic.ttf` extracted from my Windows 10 install.  Should have all the characters MangaGamer put into theirs plus the ones we need.

**Comment by tellowkrinkle** [comment]
Alright I made a small script to do the conversion in case anyone else has to do it in the future.  It's not great and requires a bit more work than the other two scripts, but we hopefully won't have to do this very often.  It's in the [UI Editing Scripts repo](
https://github.com/07th-mod/ui-editing-scripts) and has directions at the bottom of the [wiki page](https://github.com/07th-mod/higurashi-dev-guides/wiki/UI-editing-scripts).

**Comment by enumag** [comment]
Thanks, I'll read that when I get home.

Can someone get me the character list for the full atlas of 4152 characters?

**Comment by tellowkrinkle** [comment]
That zip file should have everything we need for now
I extracted the original font's character list from its MonoBehaviour file, which I posted [above](
https://github.com/07th-mod/higurashi-console-arcs/files/2321962/characterList.txt)
Then made a list that combined that with the list made from the script files, which is the 4152 character list, [here](
https://github.com/07th-mod/higurashi-console-arcs/files/2321961/combinedCharacterList.txt)
Finally, if we do need to add more characters we'll probably run out of atlas space, so [here](
https://github.com/07th-mod/higurashi-console-arcs/files/2333110/combinedCharacterList.txt) is that list with a bunch of Cyrillic and accented characters removed

**Comment by DoctorDiablo** [comment]
I found one small problem that might be more of a nitpick at this point.  The space character `　` renders a small tick at the bottom of the space when drawn in-game.  Is it possible to tweak the atlas coordinates just for that character so that it doesn't overlap with the character below?

![image](https://user-images.githubusercontent.com/20390474/44989148-ea712080-af5a-11e8-93bc-4f6d6aae2f20.png)

**Comment by enumag** [comment]
I don't really think that's nitpicking. Would be quite annoying to have it everywhere. Any idea how to fix it @tellowkrinkle?

**Comment by tellowkrinkle** [comment]
Okay no clue why it did this, but TMPro put that character off the bottom edge of the character atlas (y 2054 on a 2048x2048 atlas) so it wrapped around and clipped into a せ at the top.  Here's a fixed version
[msgothic_0_combined_fixed.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2346405/msgothic_0_combined_fixed.zip)

**Comment by enumag** [comment]
for future reference, how did you fix it?

**Comment by tellowkrinkle** [comment]
Find and replace in a hex editor
Find `0000E040 00600045` (Floats (7,2054))
Replace with `0000E040 00000045` (Floats (7, 2048))
I should be able to add it to the python program though
As for how I found the issue, I searched for `00300000` (little endian for 0x3000, the unicode number of ideographic space) in the file using a hex editor and looked at the x and y positions (which are the two 4-bit numbers directly afterwards interpreted as floats)

**Comment by tellowkrinkle** [comment]
Alright the converter script should do this automatically now, not sure if it's possible for the new places that it puts them to be inside other characters on other maps, if it has issues in the future I can change what it does with them.

**Comment by enumag** [comment]
@tellowkrinkle Your last character list (4152) is missing the same 4 kanji characters I wrote above. DD's character list (3720) does not have that issue. Is there a way to fix your list?

**Comment by tellowkrinkle** [comment]
Oops I forgot to add those
I found these extra characters in the font files of the other games: `窺鉤賎鉤鋸`
Here's a new charset, I'll generate the new asset when I'm not on battery since TMPro uses a lot of power [charsetNew.txt](https://github.com/07th-mod/higurashi-console-arcs/files/2350116/charsetNew.txt)
Onikakushi had a bunch of other stuff in its font files, but I think these are just someone selecting too large of a character range, so I don't think any of these are used in the game:
[Oni.0.dat.missing.txt](https://github.com/07th-mod/higurashi-console-arcs/files/2350121/Oni.0.dat.missing.txt)

**Comment by enumag** [comment]
Can you check if the other games have some other extra kanji characters we might want? Also what games are you talking about?

I don't think we need anything from that `Oni.0.dat.missing.txt`.

**Comment by tellowkrinkle** [comment]
Other games is all the games that aren't Onikakushi (since it had the ones in the other file)
BTW while doing that I realized that the font files aren't directly swappable between games (they have some pointer values to their atlas and material in them) so I'll update the converter program to work a bit better so we can use it to easily convert font files between games.

**Comment by tellowkrinkle** [comment]
[msgothic_0_combined_full.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2350943/msgothic_0_combined_full.zip)
Alright here's the new font file, I'll have an update to the scripts up in a few minutes.  EMIPGenerator's getting updated too, it should now properly find TextMeshProFont files in all games (though I only tested it with Hima)

**Comment by enumag** [comment]
I think we'll need to make a beta release with both the new DLL and new UI including fonts. Things are getting rather complicated here.

**Comment by enumag** [comment]
With the new UI packs this can be closed now I think.
