### ISSUE TITLE
Miotsukushi Omote Day 10 - Choices not presented

### ISSUE THREAD

**Issue by twerner** [07th-mod/higurashi-console-arcs#246]
The three choice menus in Miotsukushi Omote Day 10 did not appear, and the script proceeded for each of them without either response appearing in dialogue (causing an unnatural flow). At the beginning of the game I said to show choices, but highlight the correct ones. I have seen choices prior to now, but I'm not sure if any others were skipped.

I am on the latest patch.

**Comment by DoctorDiablo** [comment]
Can you try something?  Start a new game of Mio Omote from the beginning and answer yes when it asks about choices.  Then exit back to the main menu and use chapter jump to go back to day 10.  See if it still doesn't prompt the choices.

**Comment by twerner** [comment]
Option 1 does not show choices as intended, but also does not display the line the game chose for the player

Option 2 shows the choices as intended (I also managed to soft-lock the game by bringing up the menu during the first choice)

**Comment by DoctorDiablo** [comment]
Just pushed a fix for this.  Now if you have choices disabled it'll display the option the system went with.  Sorry it took forever to get around to this.
