### ISSUE TITLE
TsukiOtoshi

### ISSUE THREAD

**Issue by Mikulovers** [07th-mod/higurashi-console-arcs#26]
![bug](https://user-images.githubusercontent.com/39219285/39958438-1530e456-5603-11e8-82d0-5c5396bbfd29.png)
The text says "are you out shopping or something?" But Im pretty sure Keiichi answers to Oishis question which should be something like "Isnt she out shopping or something?"

**Comment by DoctorDiablo** [comment]
Just pushed a fix for this.  If you find anything else, feel free to open another issue.
