### ISSUE TITLE
Taraimawashi Release

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#28]
@enumag I've got all the script work complete for Taraimawashi.  Can you grab the latest "tara_" scripts from master and run them through the compiler?

@ItaloKnox The console arcs installer is already pointing to the new server, right?  After the scripts are compiled, we'll need to upload the new archives to the server.  Do you want to give me server access, or should I just send the files to you?

**Comment by ItaloKnox** [comment]
Yes, I plan on giving access to you and a few more. I just need to set up the SFTP/SSH user. I'll see if I can get this done tonight.

**Comment by enumag** [comment]
@DoctorDiablo Just returned from my vacation. I'll try to find some time tomorrow to do it. Sorry for the delay.

**Comment by enumag** [comment]
@DoctorDiablo Is there some reason why you used backslashes instead of normal slashes in Tarai scripts?

For example

```
DrawScene("background\y_kawa3", 1000 );
```

instead of

```
DrawScene("background/y_kawa3", 1000 );
```

Do the backslashes even work on linux? Are you sure `\n` in `portrait\night\...` is not interpreted as newline?

**Comment by DoctorDiablo** [comment]
Ah, my mistake.  These are the first set of scripts I generated based on the Sui xml, and I must've just generated the slashes wrong.  That'll probably fail on Linux.  The \n shouldn't be a problem though because it doesn't make any sense to do newline expansion on file names.

Do you have an easy way of replacing the backslashes with forward slashes?

**Comment by enumag** [comment]
@ItaloKnox Your turn:

[tarai.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2232807/tarai.zip)

For voices, merge the generated directory into the current console arcs voice patch.

For sprites, just pack the CG directory (ignore CGAlt) and send them to @DoctorDiablo. He'll need to add backgrounds and other images.

**Comment by ItaloKnox** [comment]
CG: http://nijino-yu.me/ddl/ConsoleArcs-CG.7z
Voices: http://nijino-yu.me/ddl/ConsoleArcs-Voices.7z

These are currently hosted on my private server. Don't forget to tell me when the new chapter is ready for release so I can pull them to our server. @DoctorDiablo can upload his completed CG pack in the developer folder in our server, upload the whole file somewhere else (such as here on Github) or just give me the missing files to update the pack. Any of them is good, but don't forget to keep me updated.

**Comment by DoctorDiablo** [comment]
@enumag Two things I noticed while doing some testing:

- The Tarai scripts are missing the character name tags
-  The voice folder looks a little weird because the Tarai scripts are pointing to voice/ps3/ but the older arcs are pointing directly to voice/.  This does work as-is, but it'd be nice if it was consistent.

Aside from that though, everything seems to be working fine.

**Comment by enumag** [comment]
@DoctorDiablo Yeah, those two issues are actually related. The script assumes the ps3/ prefixes are there. I'll fix the game scripts. Could you change your utility that generates the scripts from the Sui XML like this?

1) add `ps3/` to all voices
2) convert all voice paths to lowercase

**Comment by enumag** [comment]
Game scripts should be fine now.

**Comment by DoctorDiablo** [comment]
Tarai has been released release, so I'm marking this closed.

@ItaloKnox You can remove those files from your server now.
