### ISSUE TITLE
Font problems 

### ISSUE THREAD

**Issue by Calavera39** [07th-mod/higurashi-console-arcs#29]
Instead of a normal font  i have a pink weird font. Sorry for my English.
P. S. I have Windows XP on my PC.
![default](https://user-images.githubusercontent.com/41876283/43370383-c134f5c4-9386-11e8-8bf8-3c545367f7bd.png)
![default](https://user-images.githubusercontent.com/41876283/43370389-e7389f50-9386-11e8-98dd-c8142e6a9895.png)

**Comment by DoctorDiablo** [comment]
Looks like it's trying to render the text in a font that doesn't support these characters.

Is your operating system language set to something other than English?  Try changing your system locale to English and that might get it displaying the font correctly.

**Comment by enumag** [comment]
@Calavera39 Does the vanilla (unpatched) version of Himatsubushi have the same issue?

**Comment by Calavera39** [comment]
@enumag  Yes and It looks like only Himatsubushi has such the problem

**Comment by enumag** [comment]
Since it's a problem with the vanilla version, you should report it to MangaGamer instead. If they do resolve it, let us know. Thank you.
