### ISSUE TITLE
Patch is full of leftover stuff from Himatsubushi

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#3]
There are a lot of limitations of the current patch as a result of tweaking the installation of Himatsubushi to create the Console Arcs installation:

- The titlebar at the top of the window in windowed mode says Ch. 4 Himatsubushi.
- ~Console Arcs and Himatsubushi both save in the same folder (higurashi04)~ Fixed in v4.0.0
- ~The Extras menu on the main screen is full of stuff for Hima that doesn't work with the patch (Chapter Jump, TIPS, and the cast review)~ The Extras menu is hidden in the latest version of the dll
- ~The executable is named HigurashiEp04.exe and the files are in the HigurashiEp04_Data folder.~ Not needed
- And this is more of a feature request than a defect, but it would be nice if the executable used a unique icon instead of the Rika image that HigurashiEp04.exe uses.

**Comment by ItaloKnox** [comment]
I think the four starting points could be solved by reverse engineering the .exe and the .dlls. The game is made on Unity, so lots of stuff can be found (and edited) in the dlls.

The last point can be easily solved by making a icon and changing it. I could try to make it but I didn't play this chapter yet, so I don't know which character would be cool to use.

**Comment by enumag** [comment]
@P-Chang Could you look into this? I think you might be able to fix some of these issues.

There is no need to rush though, we won't really need these fixes until @DoctorDiablo is done with translating Kageboushi. I think it's enough if you look at this a month from now or even later.

**Comment by P-Chang** [comment]
@enumag 
I already found the way to increase "Tips", but I didn't find the way to control unlocking logic.

Tips could be increased infinitely, but sprite may have limit.

I want to add separated chapter jump menu for console arcs, and I looked over chapter jump class and grep "Day" and "日目" and chapter name like "onikakushi" and "鬼隠し" in source code. but there are no line that use these strings, strangely.

probably, MG make them in Unity GUI and it is stored in Assets Bundle. Perhaps, I need to prepare another codes for it, and I don't good idea for it yet.

I remember moving Assets Bundle to different chapter change titlebar. So changing titlebar is possible in Assets Bundle Modding. But I don't understand Assets Bundle without simple sprite swapping.

**Comment by enumag** [comment]
Tips would be nice to have but it's not a priority since we implemented them using different approach.

Not sure how chapter jump works. I thought it would just jump to the beginning of a specified file?

Personally my main concern is the usage of the same save directory as Himatsubushi. Is that possible to fix?

**Comment by P-Chang** [comment]
> Not sure how chapter jump works. I thought it would just jump to the beginning of a specified file?

Sure. But probably there are line that have list of chapter, I couldn't find it.

> Personally my main concern is the usage of the same save directory as Himatsubushi. Is that possible to fix?

I've never tested it. but it sounds like simple if it is only maindata that control entire progress.

**Comment by DoctorDiablo** [comment]
Chapter jump would be difficult because I'm planning to eventually have all 10 arcs in this release together and each arc has 10 or more chapters.  So we'd have to build a way to scroll through a huge list of chapters.

**Comment by P-Chang** [comment]
Actually, I cannot even find the way to change chapter name.

**Comment by InochiPM** [comment]
If anyone is having an issue over the icon being rika, I changed the icon to Oishi which kinda seemed appropriate to me lmao. 

[Box - Oishi icon MAC/WIN](https://app.box.com/s/syvykkk3k7s8v8ctz6ygyp8njcwv57q7)

But i had a sugetion about the chapter select menu, Why not make it look like the old menus from the original full bundled version of higurashi? 
![image](https://user-images.githubusercontent.com/13459080/34459254-189e25b6-edb9-11e7-99d3-83bf60583c81.png) 
& 
![image](https://user-images.githubusercontent.com/13459080/34459259-3a05e388-edb9-11e7-90ab-c07a1ce19e3a.png)

**Comment by DoctorDiablo** [comment]
It would be cool to do it that way, but we're a bit limited by the engine.  The chapter select screen is repurposing the choice selection function, which is difficult to modify.

**Comment by tellowkrinkle** [comment]
I know for the Mac version, the name that gets used for the titlebar (which also decides the save directory name) is stored in the `CFBundleName` entry of the `Info.plist` file in the app bundle (These are mac specific).  For other OSes, does replacing the `globalgamemanagers` file with 
[this](https://github.com/07th-mod/higurashi-console-arcs/files/2551565/globalgamemanagers.zip) work?

**Comment by enumag** [comment]
@tellowkrinkle I tried replacing the file on windows. The result is kinda funny - it did change the title but broke the game completely at the same time.

![hima](https://user-images.githubusercontent.com/539462/48046060-28750580-e193-11e8-824d-3dabb5f47993.png)

Since this kind of pink errors usually appear when we put win assets file on mac or vice-versa, maybe you need to edit the `globalgamemanagers` from windows instead so here it is:

[HigurashiEp04_Data.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2551791/HigurashiEp04_Data.zip)

**Comment by tellowkrinkle** [comment]
Ahh forgot about that issue [globalgamemanagers.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2552020/globalgamemanagers.zip)

**Comment by enumag** [comment]
@tellowkrinkle Yeah, that works. How did you edit the file? How did you find out the title is there?

Anyway let's review the remaining notes from the first post:

> The Extras menu on the main screen is full of stuff for Hima that doesn't work with the patch (Chapter Jump, TIPS, and the cast review)

@DoctorDiablo You have made some changes around TIPS, so can that be considered solved? Are Chapter Jump and Cast Review still an issue? If yes, what would you like to do about them?

> The executable is named HigurashiEp04.exe and the files are in the HigurashiEp04_Data folder.

@DoctorDiablo I don't really think this is a problem. I mean we're patching himatsubushi so this is to be expected...

> And this is more of a feature request than a defect, but it would be nice if the executable used a unique icon instead of the Rika image that HigurashiEp04.exe uses.

@DoctorDiablo The icon is usually packed in the exe file itself afaik and there are some tools to change those icons. If you give us an icon you want to use we should be able to replace it I think.

**Comment by tellowkrinkle** [comment]
I found the text with `grep -r Himatsubushi .`, `globalgamemanagers` is a Unity asset bundle, so I opened it with UABE and did something similar to how `UnityTextModifier.py` works (it won't work directly yet because it currently searches for an English and Japanese string immediately following each other, I'll fix it to work with single language strings a little later)
For editing the `Info.plist`, yeah it's just an XML file, looks like this [Info.plist.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2555327/Info.plist.zip).  The (slightly) bigger issue will be directing users to install the file properly, because it's at a higher level than the directory they'll be trying to shove everything else into: 
![image](https://user-images.githubusercontent.com/3315070/48099553-8f230f00-e1e5-11e8-9c46-077b77f0daab.png)

**Comment by tellowkrinkle** [comment]
Oh I guess while we're at it, here's edited info plists for Onikakushi and Watanagashi that change their titlebar names from `Higurashi01` and `Higurashi02` to slightly more reasonable names (for some reason Tatarigoroshi+ had the right names but the older games didn't)
[Onikakushi_Info.plist.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2555415/Onikakushi_Info.plist.zip)
[Watanagashi_Info.plist.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2555417/Watanagashi_Info.plist.zip)
And here's some icon files I made from the images used by the Windows installer to avoid the duplicate Himatsubushi icon.  No clue if they look like current Windows ones though.
[HigurashiIcons.zip](https://github.com/07th-mod/higurashi-console-arcs/files/2555430/HigurashiIcons.zip)
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3315070/48100546-60a73300-e1e9-11e8-8c9b-06a00a3f62b8.png">

**Comment by DoctorDiablo** [comment]
I tested that globalgamemanagers asset file and it worked perfectly.  We could bundle it with the UI asset file, but I think it would be better to make it a separate archive, since Himatsubushi and Console Arcs currently use the same asset file.  Or we could make it part of the main patch file with the scripts and dll, which would probably be easiest.

The Extras menu was removed from the Console Arcs in one of the recent dll changes, so that part no longer matters.

I'm cool leaving the filename on the executable as-is.  I crossed it off the list.

The [.ico files used by the installer](https://github.com/07th-mod/Higurashi_Installer_WPF/tree/master/Higurashi_Installer_WPF/Resources/07th_icons/ico) should be good enough for the Windows side.  Looks like a tool called Resource Hacker can modify the icons for .exe files.  Do we know if the steam/MG/GOG versions all use the same executable?  That would simplify maintenance and installation.

And I'm not very well versed in Macs, but it looks like Tellowkrinkle's .icns files should work for the mac version, we just need to update the installation instructions so the users know what to do.

**Comment by enumag** [comment]
SHA1 checksum for MG exe file and steam exe file is the same for Hima so I'm guessing we can have just one exe per chapter. We will most likely want to change the icons for all chapters to be honest - currently they seem to have different styles and resolutions so it would be nice to unify them. Plus we could use PS3 sprites instead of MG.

![icons](https://user-images.githubusercontent.com/539462/48113413-0a72d800-e25b-11e8-9323-82b91a6b5680.png)

**Comment by tellowkrinkle** [comment]
Woah, those are completely different from the Mac versions.  Also, is Shion on both the covers to Watanagashi and Meakashi? 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/3315070/48116735-a33e2f00-e22c-11e8-8525-2f584e04b1ca.png">

Anyways, I might work on a Mac installer once I'm done with the history update

**Comment by tellowkrinkle** [comment]
Title change on linux will be done with the updated globalgamemanagers, which *is* in the same directory as a bunch of other stuff (like `nipah.json`, which we shouldn't actually need because the title change should also update the save directory for linux)

**Comment by DoctorDiablo** [comment]
The updated icon and title text are implemented for Windows as of the v5.0.0 release, but I believe we still need to do the same for Mac/Linux.

**Comment by DoctorDiablo** [comment]
I think everything here is already implemented.
