### ISSUE TITLE
Issue with new "UI" package

### ISSUE THREAD

**Issue by Green-Cat** [07th-mod/higurashi-console-arcs#30]
After updating to the 4.0 version of the patch today I was met with many UI elements and all letters replaced with pink squares (see image below). Version 3.0 worked perfectly on my mac.

<img width="965" alt="screen shot 2018-08-04 at 18 43 18" src="https://user-images.githubusercontent.com/3328823/43678720-10946532-9819-11e8-87a4-7b2e9af4186c.png">

<img width="965" alt="screen shot 2018-08-04 at 18 51 56" src="https://user-images.githubusercontent.com/3328823/43678723-14c99802-9819-11e8-8207-7e88c09cf2af.png">

By downloading a fresh copy of the game off steam and copying in all the non-image/sound files one by one, I was able to narrow down the issue to the "sharedassets0.assets" file of the manual install "[UI](https://07th-mod.com/rikachama/Himatsubushi-UI.7z)" archive. Launching the game with the original version of that file results in all the text appearing correctly.

It is probably also the cause of the issue which was reported in #29.

**Comment by ItaloKnox** [comment]
I just went ahead and deactivated the UI mod for Tarai until we find out what is going on.

**Comment by enumag** [comment]
Hmm... Maybe I accidently swapped Win and linux UI files? 🤔

**Comment by DoctorDiablo** [comment]
Ah, this might be an issue with the instructions.  I only linked to the [Windows](https://07th-mod.com/rikachama/Himatsubushi-UI.7z) version of the UI mod on the instructions page.

Try dropping the [Mac/Linux](https://07th-mod.com/rikachama/Himatsubushi-UI_UNIX.7z) version of the UI mod in there and see if it works.

**Comment by ItaloKnox** [comment]
I guess that's it. I only noticed he was running OSX after your comment.

If you are comfortable with it, I can move the console arcs instructions to the wiki. All games are now following the same instructions, so it requires very little editing in order to have them all in the same place.

**Comment by DoctorDiablo** [comment]
Yeah, I think it's time we made everything consistent.  The separate instructions were a carryover from the days when console arcs had its own weird installation steps.

**Comment by Green-Cat** [comment]
The UNIX and Windows archives seem to contain the exact same files.
I ran a sha256 checksum on both files in the archives, and I got the same result on both.

sharedassets0.assets: 7f59bdd2195e1c7d19055231f2d14407ac93f989fc7c93e3516919df82774303
sharedassets0.assets.resS: aba8339e7b8043a2fbe8dec65ecc1fdc2e2a486259877d18c57c0a839a5cce91

**Comment by ItaloKnox** [comment]
@DoctorDiablo 
I changed the wiki to add the console arcs downloads and a couple extra instructions.

@Green-Cat 
There's a chance I did something wrong when migrating and remaking the packs. I'll remake the UI mod right now, give me a few minutes.

**Comment by ItaloKnox** [comment]
Done. Unless the problem came from the source of the files, this should fix it.

**Comment by Green-Cat** [comment]
Weird looks like the UNIX and Windows archives still both have the Windows versions of the files.
I dug around a little more and extracted both the original "sharedassets0.assets" file from steam and the one from the UNIX archive above, and compared the contents of the extracted files.
There are several references to OpenGL and Metal (a mac os UI library) replaced with DirectX dll names inside "TMPro_SDF.shader" and "TMPro_SDF-Mobile", the files responsible for the text mesh.

<img width="856" alt="screen shot 2018-08-05 at 17 56 25" src="https://user-images.githubusercontent.com/3328823/43687646-f94a02e0-98d8-11e8-9c4f-950d0ca90b2a.png">
Inside "TMPro_SDF.shader" Left is from the UNIX archive, right is the orignal file from steam 

<img width="838" alt="screen shot 2018-08-05 at 17 56 42" src="https://user-images.githubusercontent.com/3328823/43687647-f9615f80-98d8-11e8-8bd7-e17005d7015e.png">
"TMPro_SDF-Mobile.shader"

Looks like the windows version of those files accidentally got into the UNIX version of the asset bundle somehow.

**Comment by ItaloKnox** [comment]
I just sent a new version of the Himatsubushi UI to the server. This one should actually fix the issue. [Get it here](https://07th-mod.com/rikachama/Himatsubushi-UI_UNIX.7z) and let me know what happens.

**Comment by Green-Cat** [comment]
@ItaloKnox Works perfectly, thank you!
