### ISSUE TITLE
mistranslations in miotsukushi omote

### ISSUE THREAD

**Issue by msksk** [07th-mod/higurashi-console-arcs#308]
I'm not native English speaker so these may be not natural translations.
I will add comments after reading other texts.

omot_009_2.txt

 Line 214
「図書館なのです。なんだか変な人たちとわいわい、楽しそうに話していたのですよ」

>  "なんだか変な人たちとわいわい、楽しそうに話していたのですよ"
> " Some weird people were talking all excitedly and making a lot of noise."

Rika says "She were talking with some weird people ... a lot of noise."
This is not an obvious mistranslation.

 Line 501

> "やっぱり、思ったことはあったんだな。"
> "...I never expected it to go like this."
	
Keiichi says in his mind "...As I suspected, She has considered to work once." in Japanese correctly.
"She"( =Shion) and "to work there" is omitted in Japanese.

Line 514

> 「…事が大きいだけにそれがはっきりしないと、悪いですけど言う通りには従えませんよ」
> "...It certainly sounds like a big deal, but it's not clear to me why you're telling us."

Shion says "...It certainly sounds like a big deal, so I'm sorry but I can't accept it until it's clear to me."

**Comment by msksk** [comment]
"やっぱり、思ったことはあったんだな。"
Keiichi says so in his mind. supplement just in case.

omot_009.txt

Line 585

> "彼女のため、と言いつつ実は自分の後ろめたさを転嫁しているだけでしかないと、心のどこかから『俺』が叫んでいるのが聞こえた。"
>  "Somewhere deep in my heart, I heard "myself" screaming something like that behind my back."

"彼女のため、と言いつつ実は自分の後ろめたさを転嫁しているだけでしかない(と、)" is totally omitted in English.
this is like "I profess 'for the sake of her',  actually just to excuse my guilty feeling." in Japanese.

Line 642

> "ガラの悪いと言っても、そこいらにいる不良とか怖い人とか、そういうレベルではない。…明らかに本職のオーラが漂っている。"
> "Even though I say he looks like a bad guy, he's not nearly on the level of truly scary bad people. ...He clearly had an aura of professionalism."

”本職” is Japanese argot meaning  a man who belongs to Yakuza. So "He clearly had an aura of mobster" or simply "Yakuza".


Line 868

> "脳内で慎重に次に発する言葉を捜す。この、いかにもその『スジ』っぽい怖そうな人を、何と形容すればいいのか。"
>  "I carefully scanned my brain, searching for what else to say. How do I describe this scary-looking <i>muscle</i> man?"

”そのスジ” is not muscle. this is also an argot that means "affiliate of Yakuza"

**Comment by msksk** [comment]
omot_009_3.txt

Line 26

> "それに上納金においそれと手をつけられては、組としてのメンツもある」"
> "And there certainly are dishonorable ones who would be interested in embezzling treasury funds."

More literally, "And it would be dishonorable for us that treasury funds would be easily embezzled."

**Comment by msksk** [comment]
omot_010.txt

Line 96
> あの時、私に運命を打ち破る力…いいえ、その思いと、意志があれば。"
> "At that time, the power to break my destiny... No, if only I thought that the will was there."
"At (...) destiny.. No, if only I had thought and will to do it." is more accurate.


Line 188

> 「…まぁ、運命ってより、その可能性をな。",
> "...Well, that fate is a possibility."

Keiichi seems to refer to Rika's remark of Line 96.
He says "...Well, I believe not your destiny, but possibility her doing so."


Line 231

> "Then we'll have to be careful about how we handle Rena."
> 「じゃあ、レナにそのことを注意しておかないとな」

He says "Then we'll have to warn Rena of that."

Line 256

> 「まさか、またこのまま見過ごした方がいい…",
> "There's no way we can overlook problems like this.. 
> なんて、考えてないよな？」
> Don't you think so?"

また(again) is missing.
"It's better for us to overlook problems like this...
surely you won't think so again?"


Line 361

> レナは確か、自分のことがきっかけで両親が離婚して、そのことで負い目を持っていたはずだ。
>  "Rena certainly has a negative outlook since she blames herself for her parents' divorce."

"Rena certainly has been blaming herself for her parents' divorce due to a problem about her."
more literal.

Line 393

> "もしこのことを教えたら、レナは敵意をそのまま殺意に変えてしまうのではないでしょうか…？」
> "What if Rena gets hostile and malicious after we tell her about this...?"

"Rena gets hostile and malicious if we tell her about this, right...?"

Line 405

> それに相手を殺しても何の解決にもならないし、それどころか不幸になるってことくらい、レナにだってわかるさ」
> " We have to make Rena understand that killing her enemy won't solve her problems. In fact, it'll only make her unhappy."

opposite nuance.
"I believe Rena will understand that killing ... problems, and that it'll only make her even unhappy."

**Comment by msksk** [comment]
omot_010.txt

Line 1162

> …ほんとは喜一郎に予定を確認した。
> 今日の竜宮家訪問には、魅音も一緒の方が…という提案をしてみたが、圭一がＮＧを出したのだ。
> …空気読めないってことかな。
> ...In reality, I confirmed the schedule with Kiichirou. 
> I originally suggested that Mion come along for today's visit to the Ryuugu household, but... Keiichi sternly rejected the idea. 
> ...Maybe I can't get a good read on the situation.

Accurately 
"...Maybe 'cause she can't get a good read on the situation."
"she" is Mion.
 

Line 1280

> 大丈夫だって、魅ぃちゃん。最後は圭一くん、ちゃんと魅ぃちゃんのところへ帰ってきてくれるから」
> It's all right, Mii-chan. After we're done, Keiichi-kun and I will head back to your place."

"It's all right, Mii-chan. After all, Keiichi-kun will head back to you and spend it with you." 
Rena replied to Mion's "Kei-chan, (...) these days."

**Comment by msksk** [comment]
omot_010_choice1.txt

Line 45

> レナは固い口調で、ぴしゃりと言う。目が少し怒ったように、圭一を見返していた。
> "Rena interrupted in a harsh tone. She had a slightly angry look in her eyes, so I turned back toward Keiichi."

"She had a slightly angry look in her eyes, staring into Keiichi."


omot_010_choice2.txt
Line 46
same sentence as omot_010_choice1.txt, Line 45.


omot_010_4.txt

Line 941

> "その全身はびっしょりと汗をかいて、まだ小刻みに震えている。…それでも、さっきまでの錯乱した雰囲気は影を潜め、俺と梨花ちゃんは顔を見合わせ、ほっとため息をついた。"
> "Her whole body was still trembling and covered in sweat. ...Even so, the confusing atmosphere up until now was still lurking in the shadows, so Rika-chan and I looked at one another and sighed."

"Her whole body was still trembling and covered in sweat. ...Even so, her confused look up until now no longer appeared, so Rika-chan and I looked at one another and sighed relievedly."


omot_010_choice5.txt

Line 51

> が、きっと圭一に対してレナは一瞥すると、不愉快そうに視線をそらして苛立たしげに髪をいじる。
> But when Keiichi stared at her, Rena turned away looking upset, and began messing with her hair in irritation.

But after taking a sharp glance at Keiichi, she turned away looking upset, and began messing with her hair in irritation.

Line 63

> なおも言い続けようとしたが、そんな私を圭一は手で制する。そして、話を続けた。
> "I tried to speak up, but Keiichi held up a hand to stop me."

"そして、話を続けた。" is omitted in translated sentences.
This is like "And, he resumed discussing."

omot_010_choice6.txt
Line 61
same sentence as omot_010_choice5.txt, Line 63.

**Comment by msksk** [comment]
I have to comment too much at this rate, so I will do pull requests from this onward.
Maybe I needlessly pointed out even slight differences between Japanese texts. 
Please reject them if original translations are more natural than my ones.

**Comment by DoctorDiablo** [comment]
Don't worry, I appreciate you pointing things out.  I'll try to get to these today. If you know how to submit pull requests, that does make it a little easier.

**Comment by msksk** [comment]
Thank you for replying. I'm not sure if it's possible to read all, but I will try to read and pull requests as long as time allows, including other chapters.

**Comment by DoctorDiablo** [comment]
Just pushed fixes for all the above issues. Feel free to do more if you'd like.
