### ISSUE TITLE
Inconsistency in flow.txt

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-console-arcs#33]
I just noticed something odd in flow.txt. There are some [lines](https://github.com/07th-mod/higurashi-console-arcs/blob/efa69a940dcdfeac606d5cc733a335b1c8b394e7/Update/flow.txt#L118-L270) about the days of Someutsushi but there is nothing like that for the other chapters there. Are these even used? Why are the other chapters missing?

**Comment by DoctorDiablo** [comment]
That code isn't used anymore, so it can be safely removed.  I should probably do some housekeeping on these old scripts.

Handling the chapter flow that way caused problems somewhere down the line (maybe when tips were first implemented?), so I migrated to the system used today that handles all that logic inside chapterselect.txt.
