### ISSUE TITLE
Yoigoshi Translation Improvements

### ISSUE THREAD

**Issue by idealpersona** [07th-mod/higurashi-console-arcs#36]
I just directly committed typo fixes but these are more opinionated suggestions that are all up to you @DoctorDiablo . This is me largely only proofreading the english text and only rarely looking at the japanese source.

In the text below mostly there's `##` delimiting my notes from the quoted text.  it's just somewhat how i was taking notes and it's not super strictly following this format.  I can format this a lot better in the future... 

I found a few untranslated lines and gave my noob interpretation.

Yoigoshi 001
```
## missing line opinionated translation: ## まさかとは思うが、そんな幸せな身分で若い反町さんと『あやしい』関係だったりしたらあのヤロー、呪い殺してやる…。 ## It seems unthinkable. For someone at that point in life to have such a "suspicious" relationship with young Sorimachi-san - such a person would certainly be cursed.
## Missing line opinionated translation ## 俺は踵を返すと、歩き出す。 ## I turned to walk back toward the car.

Even now, I keep a hand against the window at all times because the seatbelt can't keep me sufficiently stable.  ## i rephrased this, hopefully that reads better.  "insufficient" just sounded stiff especially in that context.
(There's no saving us if we plunge down...) ## I suggest "down there..."
Are those ruby earrings shining in her ears? They have a luxurious aesthetic, not gaudy at all, and they seem suitable for engaging in intellectual activity ## "engaging in intellectual activity" sounds weird
I don't have nearly the keen eyesight necessary to ride a motorcycle.  ## Huh? where did a motorcycle come from?
Her father must be so proud of her. ## Converse? "must be proud of her father" or "must be proud of him"
"...Ah, but the truth is, you don't actually believe in that stuff, right?"  ## (Believe in "that stuff" or believe what he just made up? sounds like she doesn't believe him, not that she doesn't believe in intuition...)
 Miyuki-chan, it's the kind of thing you probably wouldn't like?" ## I know the JP makes this difficult.  Maybe "i'm not sure it's the kind..."  - i think will make it more natural.
 "Oh. Just as I thought... I shouldn't have brought up this story?" ## another wierd "?", maybe one of these options:
 ## "Oh. Just as I thought... should I not have brought up this story?" <- if seeking genuine yes/no answer
 ## "Oh. Just as I thought... I shouldn't have brought up this story, should I have?" <- if suggestive of an affirmative answer, same with below
 ## "Oh. Just as I thought... I shouldn't have brought up this story, huh?"
 ## "Oh. Just as I thought... I shouldn't have brought up this story, right?"
```

**Comment by DoctorDiablo** [comment]
Don't worry, I can make do with this as long as I have the text from the line in question.

But that suggestions feature looks pretty cool if you'd like to do it that way.

**Comment by DoctorDiablo** [comment]
@idealpersona All these items have been addressed in the latest commit.  I've made it through editing the first 2 chapters so far.  If you're interested in doing any more, you can grab all the files necessary to run it in the Yoigoshi Release issue thread.

**Comment by idealpersona** [comment]
Cool sounds good.  I may start on ch2 tonight.  I'll grab the files and let you know if i have any issues.

**Comment by idealpersona** [comment]
Submitted a pull request for Tip 001.

For some reason the rain sound cuts out every 3-4 seconds for a split second.  As if it's looping the same audio clip every 3-4 seconds.  That will probably drive any reader a little crazy.  Let me know if we need to do some audio processing to create a longer track or something.

**Comment by DoctorDiablo** [comment]
Some audio editing to extend those tracks would be nice.  Check the BGM folder for the handful of really short files.

There were a couple files like that in the earlier arcs that were so bad I just replaced them with equivalent tracks from the PC version.  That's always an option too.

**Comment by idealpersona** [comment]
Yoig 002

`Oh, I'll come too`.
"oh" can probably be refined to "okay" or something, unless it's meant to be that.

`We carefully pointed our lights toward every corner`
This paragraph feels verbose; seems like it could be made more concise.   Maybe that they pruned every corner of the driver and passenger seat before checking the back, instead of being more stepwise in the description.

`pink-toned telephone`
"pink toned" just sound strange to me, at least in this context

Tips 003

`If you're unfamiliar with the area, you can probably make it there by dawn?`
It's a little confusing how much this is a question and how much this is a statement with a level of uncertainty.  If that's intentional, then that's fine; it is obviously a condescending or sarcastic statement.

**Comment by DoctorDiablo** [comment]
Marking this closed since @idealpersona is done editing for now.

If you ever decide you want to do more, feel free to reopen it.
