### ISSUE TITLE
Text going out of text borders

### ISSUE THREAD

**Issue by mecha-yota** [07th-mod/higurashi-console-arcs#365]
Someutsushi 
![image](https://user-images.githubusercontent.com/79519087/108844510-a7f1a180-75f5-11eb-84ed-1e13d495b756.png)
![image](https://user-images.githubusercontent.com/79519087/108844355-72e54f00-75f5-11eb-9e51-97b036ce99a2.png)
![image](https://user-images.githubusercontent.com/79519087/108844376-78db3000-75f5-11eb-919c-2b8d646d5337.png)
![image](https://user-images.githubusercontent.com/79519087/108844393-809ad480-75f5-11eb-8930-c6fd9b665c51.png)
![image](https://user-images.githubusercontent.com/79519087/108844412-885a7900-75f5-11eb-8d5b-45553a361b1e.png)

**Comment by mecha-yota** [comment]
Kageboushi (will update)
![image](https://user-images.githubusercontent.com/79519087/108844656-d7a0a980-75f5-11eb-9807-c7b8f74c9d32.png)
![image](https://user-images.githubusercontent.com/79519087/108844673-df604e00-75f5-11eb-8b32-8947d54eaf2d.png)

**Comment by DoctorDiablo** [comment]
Thanks for pointing these out, and sorry I took so long to get to them.  Just pushed fixes for all of these.

If you find any more, feel free to post them.

**Comment by mecha-yota** [comment]
no problem, I’ll post more if I find any when I resume reading

  
>Воскресенье, 28 февраля 2021, 5:27 +03:00 от DoctorDiablo <notifications@github.com>:
> 
> 
>Thanks for pointing these out, and sorry I took so long to get to them. Just pushed fixes for all of these.
>If you find any more, feel free to post them.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Владимир Алтухов

**Comment by DoctorDiablo** [comment]
Going to mark this resolved because it's been a while and no other issues have been reported. Thanks for the help!
