### ISSUE TITLE
Miotsukushi Omake untranslated copy and other issues

### ISSUE THREAD

**Issue by FatesTimelines1337** [07th-mod/higurashi-console-arcs#371]
The All Star Review Session for Miotsukushi appears to have been forgotten and is currently untranslated.

EDIT: Turns out that was a leftover file since the actual translation was done on a renamed copy. tips.json still points to the old file.

Some lines in omot_omake.txt are attempting to retrive backgrounds in the folder path "background/a/" which does not exist. This folder path also appears in other files.

**Comment by FatesTimelines1337** [comment]
There is also calls within the latest release files for file paths to "backgrounds/c/" and "background/t/".

**Comment by DoctorDiablo** [comment]
That's something I still need to take care of.  The script file for the Mio omake is based on the PS3 version, but there were some changes in the Switch version and I want to incorporate those (or maybe let the user play whichever version they want).  So it's kind of been on hold until I can figure that out.

**Comment by DoctorDiablo** [comment]
This is finally implemented properly. I'll make sure it's included in the next release.
