### ISSUE TITLE
Mistranslation in Hint VII

### ISSUE THREAD

**Issue by masagrator** [07th-mod/higurashi-console-arcs#383]
As I didn't know how you will try to tackle this, I'm writing this as issue instead of PR.

https://github.com/07th-mod/higurashi-console-arcs/blob/96e456d5d21b835b4be93a7bcfc48df8f375a4e7/Update/kake_099.txt#L36

"World of the 1940s" - this is wrong. This is 40s in Shouwa Era, so correct period is 1965-1974.

**Comment by DoctorDiablo** [comment]
Pushed a fix for this. Thanks!
