### ISSUE TITLE
Doesn't display the end of screen icon in text.

### ISSUE THREAD

**Issue by Aspirety** [07th-mod/higurashi-console-arcs#4]
![](http://puu.sh/wokxp/3ea17c3841.jpg)

With the other arcs, the end of the icon that appears at the end of text indicates whether there's more lines left on the screen or whether clicking will move to the next screen. In this release, there's only the "more lines" icon, with nothing to indicate the end of the screen.

![](http://puu.sh/wokwq/9cc4bca626.jpg)

This feature is very helpful to me, because I often find myself clicking until the end of the screen. What happens here is I end up clicking too far and have to go through the backlog or, worst yet if I want a screenshot I need to reload a previous save. Not sure how you'd go about it, but including this icon would be very appreciated.

**Comment by ItaloKnox** [comment]
I don't think we made this change in particular but maybe @enumag can look into this issue.

**Comment by enumag** [comment]
The icon to be displayed is determined by Line_WaitForInput vs Line_Normal. Some seems to only use Line_WaitForInput. I should be able to fix it by writing a script that would replace the last Line_WaitForInput with Line_Normal before any ClearMessage(); command.

**Comment by ItaloKnox** [comment]
Looks good to me. I don't remember if we did change this but this is certainly something that would bother me.

**Comment by Aspirety** [comment]
Thanks so much guys! Keep up the great work.

We've just started reading Someutsushi for our [Rokkenjima Tea Party](https://rokkenjima.org/someutsushi-tea-party/), so we'll depending on your patch over the next couple weeks! No pressure~

**Comment by ItaloKnox** [comment]
Looks like we're reaching greater heights now. @DoctorDiablo must be happy with this, he worked through Someutsushi all by himself.

I'll make sure to release a new patch fixing this issue as soon as the script is done. Thanks a lot for reporting this.

**Comment by Aspirety** [comment]
Be sure to let me know once the patch has been released!

**Comment by Aspirety** [comment]
Do you guys have anywhere I can post typos / translation errors?

**Comment by ItaloKnox** [comment]
If you are going to post a ton of them, you can open a single issue (like this one) and keep posting them. We'll fix that as soon as we get the update, though we will only release a new version after you think you are done. We need to avoid flooding the releases but anyone can get the latest snapshot if they want.

**Comment by enumag** [comment]
@Aspirety The icons should be fixed now. Can you try it before we make a new release?

For typos/translation errors just open a new issue. Or you can suggest a change using the edit button here on github. Whichever is easier for you.

@DoctorDiablo If you translate any more chapters you don't need to worry about about these icons, I can just rerun the [script](https://github.com/07th-mod/higurashi-patch-compiler/commit/cbc4b3a7798fe8a6fdbb4fcb66a377ce614c8c3f) when you're done. Also please use `git config --global core.autocrlf true` on your machine to fix [line ending issues](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by enumag** [comment]
@Aspirety Also would you be interested in trying out our new [ADV-mode](https://vndb.org/g32) feature? It is still experimental but I'm quite satisfied with the results I achieved in Himatsubushi. Here is a screenshot what it looks like currently:

![rika](https://user-images.githubusercontent.com/539462/27284472-38c05598-54f9-11e7-9c31-5a8079b14b8b.png)

**Comment by Aspirety** [comment]
Wow that looks amazing! I'd love to try it.

**Comment by DoctorDiablo** [comment]
Awesome, happy to hear more people are reading this chapter.  Thanks @Aspirety for pointing this out.  And thanks @enumag for fixing it.

I'll package a proper release for this fix later today (Don't have access to the files right now.  At work) but if you'd like to test it out immediately, you can grab the script files directly from the repository and drop them in your Update folder: https://github.com/07th-mod/higurashi-console-arcs/tree/master/Update

**Comment by Aspirety** [comment]
Okay, the script seemed to work well! Cheers guys.
