### ISSUE TITLE
Question regarding the content 

### ISSUE THREAD

**Issue by zephyr319** [07th-mod/higurashi-console-arcs#43]
So, I played Higurashi Sui PS3 version a bit. The game starts with a policeman scene. The rest of the stuff is locked. Where does that fit into the game? And what arc is it part of?

**Comment by DoctorDiablo** [comment]
The PS3 version added a handful of prologue/epilogue scenes to various arcs throughout the series.  These were a bit spoilery, so we decided not to add them into their respective arcs.  Instead, they can all be found in the Police Case Files section in the console arcs mod.

**Comment by zephyr319** [comment]
Thanks for the answer. I apologize if I seem to be appearing ignorant but is the Police Case Files section already present in the content you guy have put out or is it a work in progress?

**Comment by DoctorDiablo** [comment]
Yep, it's included in the current version of the mod.  We added it about a month ago.

**Comment by zephyr319** [comment]
Thanks again.
