### ISSUE TITLE
Miotsukushi Omote Day 26 sound effect/scripting error

### ISSUE THREAD

**Issue by Tymaeus** [07th-mod/higurashi-console-arcs#489]
In Mitotsukushi Omote Day 26, around line 10470, the scene shifts from Shion's group in the car to the final confrontation at the shrine, however, the "car driving" sound effect can still be heard in the background even after the transition.
Sound effect stops playing after Rika falls to the ground around 10860.

**Comment by DoctorDiablo** [comment]
Fixed.
