### ISSUE TITLE
Typo in Tsukiotoshi Day 15

### ISSUE THREAD

**Issue by DogLover314** [07th-mod/higurashi-console-arcs#49]
![Capture](https://user-images.githubusercontent.com/38626341/59377054-63d64480-8d1f-11e9-8b8e-ef0b48dce155.PNG)
The line should read " You were only trying to kill Rena because you were manipulated **by** Oyashiro-sama, right?"

**Comment by DoctorDiablo** [comment]
Just pushed a fix, so it'll be in the next release.

Thanks for pointing this out!
