### ISSUE TITLE
Miotsukushi Day 26 translation corrections

### ISSUE THREAD

**Issue by Tymaeus** [07th-mod/higurashi-console-arcs#490]
This isn't really an issue, but I didn't know where else to put this.
Since I am unable to send any pull requests to omot_026.txt, I have separately compiled the remainder of my translation corrections for the file in this issue.
The correction markup is as follows:

#1: (English Line number)
#2: (Japanese text)
#3: (Corrected English text)

4894
OutputLine(NULL, "だって、あなたはこの世界に来た時から、私の身体を支配していたんだもの」",
				NULL, " After all, you've been controlling my body since you arrived in this world.\"", Line_Normal);

5211
OutputLine(NULL, "だったらもし、…もしも自分がそうでなかったとしたら、……私はこれを受け取る資格があるのだろうか？",
				NULL, "In which case... if that's not who I really am... then do I even have the right to accept it?", Line_Normal);

5509
OutputLine(NULL, "その後、赤坂に大石、入江から聞かされた言葉から…私はぐちゃぐちゃに混濁した記憶に整合性をつけて、ようやく確信した。",
				NULL, "After that, based on what Akasaka, Ooishi, and Irie told me... I sorted out my muddled memories, and was finally convinced.", Line_Normal);
		
5591		
OutputLine(NULL, "僕は、まだ今ひとつ納得できない…」",
				NULL, " Even now, I still can't come to terms with it...\"", Line_Normal);

5601
OutputLine(NULL, "今ここにあるのが、確かな現実でしょ？",
				NULL, " This is indeed reality right here and now, right?", Line_WaitForInput);

5603			
OutputLine(NULL, "　それに…落ちたのがあなたじゃなく私だったら、間違いなく死んでいた」",
				NULL, " And... if I'd been the one to fall instead of you back then, I would have died for certain.\"", Line_Normal);

5610
OutputLine(NULL, "「…ただ、かなり強引に能力が発動したせいか、沼の周りにいた圭一と山狗たちの一部も巻き込んでしまったみたいだけどね」",
				NULL, "\"...However, it seems Keiichi and the Mountain Hounds in the vicinity of the swamp got caught up in the phenomenon too, perhaps because that ability was rather forcibly activated.\"", Line_Normal);

5637
OutputLine(NULL, "「僕の意識が、梨花の身体の中に入って…その一方であなたが、その水晶の中に閉じこめられるなんて。",
				NULL, "\"My consciousness was sent to your body... while you became trapped inside that crystal.", Line_WaitForInput);

6075
OutputLine(NULL, "いや、次の世界がどこから始まるのかすら、まったく想像ができない。",
				NULL, "No, I can't even imagine from what point the next world might begin.", Line_Normal);

6153
OutputLine(NULL, "「当事者になって、困難に立ち向かうことがこんなにも辛くて、苦しくて…心と身体を切り刻まれるような大変さを伴うものだということを、理解していなかった」",
				NULL, "\"I never knew how painful it was to be a participant and confront hardships... Nor what a heavy toll it takes on your mind and body.\"", Line_Normal);
				
6160
OutputLine(NULL, "「こんな僕に、梨花を励ます資格など…ない。",
				NULL, "\"Someone like me... had no right to encourage you, Rika.", Line_WaitForInput);

6167
OutputLine(NULL, "こんな大切なことを…僕は今まで、気づかずにいたのですね…」",
				NULL, "Up until now... I never even realized something that important...\"", Line_Normal);

6483
OutputLine(NULL, "「駆け寄って声をかけても、身体を揺すっても…梨花は動きませんでした。",
				NULL, "\"Even when I shouted, ran over, and shook the body... you didn't move.", Line_WaitForInput);

6486
OutputLine(NULL, "息もしていなくて…もう、完全に手遅れでした…」",
				NULL, " It was already too late... You were no longer breathing...\"", Line_Normal);

6505
OutputLine(NULL, "でも、僕はそれ以上に…梨花と過ごした幸せな時間を、失いたくなかった」",
				NULL, " But, even more than that... I just didn't want to lose my fun times with you.\"", Line_Normal);

6557
OutputLine(NULL, "惨劇を回避する道を探すために、幾百、幾千、幾万もの時間の巻き戻しを行っているうち、…梨花はすっかり、私に依存するようになった。",
				NULL, "After hundreds, thousands, and even tens of thousands of incidences of rewinding time while searching for a way to avert the tragedy... Rika came to completely depend on me.", Line_Normal);

6583				
OutputLine(NULL, "「次はどんな感じに殺されるのかしら…くすくす」",
				NULL, "\"I wonder how it'll feel next time I get killed... Hee hee.\"", Line_Normal);
				
6608
OutputLine(NULL, "だから私は、それを逆手にとって…今度はあえて、彼女が反発するように仕向けていったのだ。",
				NULL, "So, I turned the tables on her... Next time, I reached her by enticing her to rebel.", Line_Normal);

6637
OutputLine(NULL, "それに対して、梨花は挑発されたと感じたのか…私の決め付けを否定するように、再びやる気を取り戻した。",
				NULL, "Rika may have felt provoked by that... She regained the motivation to deny my one-sided pessimism.", Line_Normal);

6667
OutputLine(NULL, "…ひょっとして私は、本来死すべき結末が定められている子を、無理やり生き長らえさせているだけなのだろうか？",
				NULL, "...Maybe I was just forcing a child who was originally fated to die to keep on suffering life?", Line_Normal);

6779
OutputLine(NULL, "幸せを掴んでみせる、と言っておきながら、結局仲間任せの気持ちを捨て去ることができなかった」",
				NULL, " As much as I said I'd grab hold of happiness, I couldn't abandon the feeling of leaving everything up to my friends.\"", Line_Normal);

6808
OutputLine(NULL, "「中途半端な思いで、命がけになってくれているみんなを巻き込もうとする考えは、とても失礼で非道なことなんだって…」",
				NULL, "\"As if to tell me the notion of asking the others to risk their lives when I'm still feeling so half-hearted is disrespectful and totally outrageous...\"", Line_Normal);
				
7044
OutputLine(NULL, "そしてここまで、私の運命を切り開いてくれたのは…間違いなく、羽入のおかげだ。",
				NULL, "And we've carved a path through destiny... All thanks to Hanyuu, of course.", Line_Normal);

7185
OutputLine(NULL, "…知らせても今さらどうにもならないし、…山頂へ至りたいという目的において、鷹野と同意見だったからだ。",
			NULL, "...It wouldn't make a difference if he informed her now... and he wanted to reach the summit just as much as Takano anyway.", Line_Normal);

7239
OutputLine(NULL, "…こちらが壊滅状態なのは向こうも知り尽くしているようだった。…人数、戦力、…全ては今や向こうに劣る。…だから全員でお出迎えがあったとしても今さら驚かなかった。",
			NULL, "...Their opponents also seemed to know everything was beyond ruin. ...Their numbers, their strength... at this point they were inferior in every capacity. So even if they met with all their forces, the outcome wouldn't have been surprising.", Line_Normal);

7251
OutputLine(NULL, "彼らも今日を全力で戦った。終始圧倒していたとは言え、体力を全て使いきり、向こうだって立っているのがやっとのはずだった。でも、…彼らは気力で立っている。",
			NULL, "They fought today with all their might. Despite being overwhelmed from beginning to end, and even though they should have exhausted all of their physical strength... they were still standing tall.", Line_Normal);
			
7349
OutputLine(NULL, "「とりあえず、…まだどんなトラップが残されているのかしらねぇが、",
			NULL, "\"At any rate... I don't know how many traps you have left, but...", Line_WaitForInput);

7412
OutputLine(NULL, "私、男性の好みには結構うるさいんですの」",
			NULL, " I'm rather picky about my taste in men.\"", Line_Normal);
			
7431
OutputLine(NULL, "「言ってくれるなぁ。",
			NULL, "\"You sure have guts.", Line_WaitForInput);
	
7434
OutputLine(NULL, "…ここのトラップは、外国の戦場でもお目にかかれない恐ろしい代物だ。",
			NULL, " ...The traps here are frightening stuff, the likes of which you'd never see even on a foreign battlefield. ", GetGlobalFlag(GLinemodeSp));

7693
OutputLine(NULL, "原因を必死で考え、怒り、罵り、嘲って、…ひとしきり騒ぎわめきまくって息が切れたときに胸にあったのは、ぽっかりとした空虚感だった。",
			NULL, "I desperately thought about the cause, got angry, sweared and sneered at it... and when I ran out of breath from all my ranting and raving, I felt a sense of emptiness.", Line_Normal);
			
7758
OutputLine(NULL, "…死んで、たまるかぁぁッ！！」",
			NULL, " ...Like hell I'll dieeeee!!\"", Line_Normal);
			
7806
OutputLine(NULL, "そして私は、私を幸せにしてくれた人の遺志を継いで、その人の偉業を日本中、いや世界中の人々に知らしめるために、今日この日まで頑張ってきたのだ。",
			NULL, "And I've been working hard up until today to inherit the will of the person who managed to give me happiness, to make his work known to people all over Japan... no, the world.", Line_Normal);
			
7818
OutputLine(NULL, "誰が高野一二三のことを思い出す？　誰が彼と、私の生きてきた証を覚え続けてくれるというのだ？！",
			NULL, "Who is going to remember Hifumi Takano? Who will continue to recall the proof that he and I once lived?!", Line_Normal);

8203
OutputLine(NULL, "　子供のくせに、人を見下すように、冷めきった目で私を見るなぁッッ！！」",
			NULL, " You're just a child! So don't give me that cold stare like you're looking down on me!!\"", Line_Normal);

8311			
OutputLine(NULL, "でもね、そんな立場に来ることができたから、わかったことがある」",
			NULL, " But, it's because I reached that position that I've come to an understanding.\"", Line_Normal);
			
8361
OutputLine(NULL, "あなたは心の広い人ね、——なんて賛辞の言葉っ？！」",
			NULL, " How compassionate of you. ...Trite compliments such as those?!\"", Line_Normal);

8438
OutputLine(NULL, "　ど、どうして、さっきからッ…！！」",
			NULL, " Wh-why? Why do I keep missing...?!!\"", Line_Normal);

8548
OutputLine(NULL, "運命を信じ、自ら神にとって代わろうと思うのなら、その正しさを己の手で見せてみろッ！！」",
			NULL, " If you believe in fate and wish to claim the seat of a god for yourself, then prove to me you're right with your own two hands!!\"", Line_Normal);

8679
OutputLine(NULL, "「か、神だかなんだか知らないけど！",
			NULL, "\"I-I don't know if this is the work of a god or whatever, but...!", Line_WaitForInput);

8760
OutputLine(NULL, "まして他人の屍の上に自らの玉座を築いたところで、そんなものは酩酊の幻！」",
			NULL, " If anything, that was an intoxicated illusion from the moment you built your throne on the corpses of others!\"", Line_Normal);

8994-8997
OutputLine(NULL, "あなたがレナの目を覚ませたように、私も自分の運命の強さを信じる。",
				NULL, "Just like when you opened Rena's eyes, I'll show you the strength of belief in my own fate.", Line_Normal);
	} else {
		OutputLine(NULL, "あなたが羽入の目を覚ませてくれたように、私も自分の運命の強さを信じる。",
				NULL, "Just like when you opened Hanyuu's eyes, I'll show you the strength of belief in my own fate.", Line_Normal);

9304
OutputLine(NULL, "「……だめだ、こりゃ」",
			NULL, "\"...This guy's hopeless.\"", Line_Normal);

9310
OutputLine(NULL, "…こいつ、これがきっかけでガンマニアに走ったりしないだろうな？　大石は定年後、再会した熊谷がガンベルトにマグナムを吊るしているサマを想像して、本気で背筋が寒くなるのを感じた…。",
			NULL, "...Is this incident gonna turn this guy into a gun aficionado? Ooishi imagined reuniting with Kumagai after retirement and seeing a magnum slung in his belt, which sent a chill down his back...", Line_Normal);
			
9328
OutputLine(NULL, "それは、赤坂のこめかみをかすって目の前のフロントガラスを直撃し、ついに無傷だったそこに、大きな蜘蛛の巣がぱっと広がった。",
			NULL, "One of them grazed Akasaka's temple and hit the windshield right in front of him, and the giant spider web finally spread into his view.", Line_Normal);

9387
OutputLine(NULL, "　豆鉄砲なんかクソ食らえ！",
			NULL, " Peashooters can just go to hell!", Line_WaitForInput);

9513
OutputLine(NULL, "目の前で爆走する車はすでに満身創痍で、運転手の疲労も重なっているのかその動きにぎこちなさが目立つようになっている。",
			NULL, "The car right in front was already covered in scratches and the driver was heavily fatigued, as was evident from the noticeable awkwardness of the car's movement.", Line_Normal);
			
9554
OutputLine(NULL, "先端の歪なロケット弾が不気味に光り、生涯に一度しか許されない獲物をしゃぶり尽くしてやろうと舌なめずりをしているように見える…！",
			NULL, "The rocket's bent tip had an eerie glow to it. It looked like it was licking its tongue at the once-in-a-lifetime opportunity to lap up its prey...!", Line_Normal);

9695
OutputLine(NULL, "「ははは、それを当てる二尉はなんなんですか？",
			NULL, "\"Hahaha, so what does that say about you since you hit him, Lieutenant?", Line_WaitForInput);

9782
OutputLine(NULL, "「僕の生徒だったらゼロからやり直しだなぁ。",
			NULL, "\"If they were my students, they'd have to start over from scratch.", Line_WaitForInput);

9795
OutputLine(NULL, "「当てようと思わない。",
			NULL, "\"Don't think about aiming.", Line_WaitForInput);

9817
OutputLine(NULL, "その射撃スタイルはわかる者が見れば惚れるものだった。がっちりと構えて激しい連射の中でもコントロールを失わない。それでいて力は入りすぎず、ゆとりも残している。",
			NULL, "His shooting style was something those in the know would fall in love with. He held the gun steady and never lost control, even in an intense firefight. And at the same time, not putting too much energy into it to leave some leeway.", Line_Normal);

10029
OutputLine(NULL, "「……く、…こ、これまでかよ…ッ！！」",
			NULL, "\"...Gh... I-is this it for us...?!!\"", Line_Normal);

10068
OutputLine(NULL, "腕は全然なまっていませんね～」",
			NULL, " Your skills haven't dulled a bit~.\"", Line_Normal);

10126
OutputLine(NULL, "あの、…実は隠していたんだけど、僕は——」",
			NULL, " Well... the truth is, I've been keeping this a secret, but...\"", Line_Normal);

10242
OutputLine(NULL, "「富竹のおじさま、…お願い！",
			NULL, "\"Mr. Tomitake... please!", Line_WaitForInput);

10290
OutputLine(NULL, "「鷹野三四以下、入江機関直属の山狗部隊の早急な制圧を開始します」",
			NULL, "\"Suppression of the Mountain Hounds working for the Irie Institute under Miyo Takano's command has promptly begun.\"", Line_Normal);

10336
OutputLine(NULL, "「話はつきましたか」",
			NULL, "\"Have you finished your conversation?\"", Line_Normal);

10386
OutputLine(NULL, "その言葉に、赤坂は複雑な表情を浮かべる。あれだけの抵抗を見せ、…その最後の最後まで抵抗を続けた山狗の末路としては、あまりに呆気ない末路だろう。",
			NULL, "Akasaka had mixed feelings on his face as he heard that. The Mountain Dogs that had continued to resist with all their might all the way until the last minute would likely meet an anticlimactic end.", Line_Normal);

10392
OutputLine(NULL, "ここにいる全員、今日一日、何度死線を潜ったかわからない。本当ならこのまま、自室にこもって泥のように眠ってしまいたいほどだ。",
			NULL, "Everyone here had no idea just how many life or death crises today had entailed. So many that truth be told, he'd just love to go home and sleep like a log.", Line_Normal);

10405
OutputLine(NULL, "「富竹さんは、…どうしますか？」",
			NULL, "\"Tomitake-san... what will you do?\"", Line_Normal);

10435
OutputLine(NULL, "僕は、…いや、僕にも、助けたい人がいるんだ」",
			NULL, " I... No, I mean, even I have someone I would like to help.\"", Line_Normal);
			
10578
OutputLine(NULL, "　お、お疲れでございますか…お、お姫様…っ？」",
			NULL, " A-aren't you tired? ...P-princess...?\"", Line_Normal);

10584
OutputLine(NULL, "荒い息を立てて、…口から血の泡を吹き出しながら、鷹野はそれでも笑みを浮かべて拳銃を構えた。",
			NULL, "Breathing hoarsely... blood foamed from Takano's mouth as she held the handgun up with a smile on her face in spite of that.", Line_Normal);
			
10700
OutputLine(NULL, "　久々に感じる自分の身体って、こんなに重いものだったかしら…？」",
				NULL, " I know I haven't been in my body for a while, but was it always so heavy...?\"", Line_Normal);

10752
OutputLine(NULL, "気を抜くと、すぐに不安が押し寄せてくる。…だから私は、必死になった。",
				NULL, "I'd be overwhelmed by anxiety the moment I let my guard down. ...So, I went into desperation.", Line_Normal);

10782
OutputLine(NULL, "　たとえどうなろうと、これが僕にとって最後の機会なのですからッ！！」",
				NULL, " No matter what happens, this is my last chance!!\"", Line_Normal);
				
11115
OutputLine(NULL, "「あなたはそんな人じゃない、古手梨花は私が一番大切な、そして一番誇りに思える友達なのです！！」",
			NULL, "\"You're not the kind of person right in front of me. Rika Furude is my most proud, most treasured friend!!\"", Line_Normal);

11277
OutputLine(NULL, "だって、私は————最強の部活メンバーの一員、古手梨花なんだからッッ！！！",
			NULL, "Because I... am Rika Furude, a member of the strongest club in the world!!!", Line_Normal);

11297
OutputLine(NULL, "　運命に屈するのは、あんたのほうだ鷹野三四ぉッッ！！」",
			NULL, " And that is why you are the one who will yield to fate, Miyo Takanooo!!\"", Line_Normal);

11520
OutputLine(NULL, "本来なら見えない、あるいは見えても不可避な時間の岐路に立たされた対象に、その意思しだいで選択の余地を与え、超常的に運命を切り開く機会をもたらしてくれるものだったのだ。",
			NULL, "The power to grant those normally invisible, or visible yet unavoidable, made to stand at time's crossroads the ability to choose depending on their will, and bestow a chance to supernaturally carve a path through fate.", Line_Normal);

11566
OutputLine(NULL, "私の体内に流れる、殺戮と凶気の本能を目の当たりにして、…絶望して、戦慄して。",
			NULL, "When faced with the evil, murderous instincts that coursed through my entire body... I despaired and trembled.", Line_Normal);
	ClearMessage();
	
11578
OutputLine(NULL, "殺されても、よかった。",
			NULL, "I would have been glad even if I were slain.", Line_Normal);

11757
OutputLine(NULL, "それは私と、羽入、そして私を取り巻く仲間たちの意志と、挑戦と、…なによりも運命が、はじめてこの鷹野三四に勝利した証左だった。",
			NULL, "It was proof that the wills, defiance... and above all else, fate of me, Hanyuu, and all my friends and allies had defeated Miyo Takano for the very first time.", Line_Normal);

11805-11810
OutputLine(NULL, "　これが、人の身の分際で、…神に挑戦した、",
			NULL, " So this is the end... of a mere human... a pitiful woman...", Line_WaitForInput);
	ModPlayVoiceLS(4, 9, "ps3/s14/09/220900305", 256, TRUE);
	OutputLine(NULL, "…哀れな女の末路って、ことなの…ッ？」",
			NULL, " ...Who challenged... god...?\"", Line_Normal);

11850
OutputLine(NULL, "…そう思われても仕方ないくらいに、私たちの関係は決してしまっていた。",
			NULL, "...Given our relationship, I couldn't blame anyone for thinking that was the case with us.", Line_Normal);

11998
OutputLine(NULL, "「私とお祖父ちゃんの研究を台無しにしたやつらがのうのうと生き続けて、必死にあがき続けた私たちは踏み潰されて、捨てられて…！！」",
			NULL, "\"The people who ruined my and my grandfather's research got to go on living without a care in the world, while we continued desperately struggling only to be crushed and abandoned...!!\"", Line_Normal);

12102
OutputLine(NULL, "そしてあなたと祖父は、その深い闇に閉ざされた、暗黒の歴史に名を残すこととなるでしょう」",
			NULL, " And you and your grandfather would leave your names on that dark chapter of history sealed away in a deep abyss.\"", Line_Normal);\
			
12159
OutputLine(NULL, "人が魂を清め、罪を贖い、過去を神の御名のもとに忘却する、祭のために生を預かりし存在」",
			NULL, "Humans are those who cleanse their souls, atone for their sins, forget the past, and move on with their lives in the name of the gods.\"", Line_Normal);

12181 & 12188
OutputLine(NULL, "　殺意と敵意で、自分を押し隠しながら——」",
				NULL, " All the while concealing yourself under bloodlust and hostility...\"", Line_Normal);
12391
OutputLine(NULL, "その顔はどこか晴れやかで、…そして、憑きが落ちたように涼やかで、清らかだった。",
			NULL, "There was something radiant in her face... She looked calm and pure, like an evil spirit had been expelled from her.", Line_Normal);

12457
OutputLine(NULL, "私にも早くこっちに来いって、何度も叫ぶ声が耳から離れないのよ」",
			NULL, " They keep screaming at me to hurry and join them, and I can't get that out of my ears.\"", Line_Normal);

12909
OutputLine(NULL, "あれだけ、憎んだ私を。",
			NULL, "Even though she hated me so much.", Line_Normal);

12930
OutputLine(NULL, "取り掛かろうとする警官隊を制して、特殊兵装の兵士たちが飛び出してくる。",
			NULL, "A group of specially armed soldiers rushed forward to break up the fight about to go down between the police.", Line_Normal);
			
13725
OutputLine(NULL, "　どうしても越えることのできなかった昭和５８年６月から次の時間へと進むことができるのよっ！！」",
			NULL, " We can move beyond the June of 1983, which we were never able to go beyond before, and advance into the future!!\"", Line_Normal);

13864
OutputLine(NULL, "「……道の行く先に何があるのかわからないのは、…みんな一緒。",
			NULL, "\"...No one knows... what lies on the road ahead.", Line_WaitForInput);

13891
OutputLine(NULL, "「そして、ほかの人の道を、同じように大切に思って、分かり合うことができる…」",
			NULL, "\"And you can understand and respect the paths others take just as much...\"", Line_Normal);
			
13954
OutputLine(NULL, "　ここで消えるほうが、私にとってはずっとわがままで卑怯よッッ！！」",
			NULL, " If you ask me, disappearing here and now would be far more selfish and cowardly!!\"", Line_Normal);

14140
OutputLine(NULL, "この雛見沢で、古手の者たちを守り続けてきた…『禍神(まがつかみ)』とともに…。",
			NULL, "Along with the \"wrathful"\ god... that has continued to protect the Furude family in Hinamizawa...", Line_Normal);
			
14201
OutputLine(NULL, "今まで、かすかに抱いていた違和感の正体に気づいて…納得する。",
				NULL, "I realized the truth behind the strange feeling I'd faintly felt for a while... and understood.", Line_Normal);

14253
OutputLine(NULL, "…『僕』は、あなたたちの仲間の一人でいても、…いいのですか？」",
				NULL, " ...Is it really be okay... for me to be one of your friends?\"", Line_Normal);

(Don't have the space to put every single one, but the scene of Tomitake protecting Takano and taking her into custody is mostly line-for-line the same as in Matsuribayashi, so it should be synced to the official TL from that. Same goes with Hanyuu's "dream" about Matsuribayashi corresponding to Hanyuu's first day at the club.)

**Comment by DoctorDiablo** [comment]
Fixes have been applied.
