### ISSUE TITLE
New Graphics packs

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-console-arcs#52]
We're currently making a big update of graphics in the main arcs:

- CG and CGAlt are now in one archive
- removed weather variants of all sprites (engine can handle it now)
- modified the path to normal sprites slightly

I have a [script](https://github.com/07th-mod/higurashi-patch-compiler/blob/master/src/Command/SpriteFilters.php) ready for it. Just let me know when you're ready for the next release and I'll run it.

**Comment by DoctorDiablo** [comment]
Incorporated into the latest release
