### ISSUE TITLE
Two minor sprites issues in Someutsushi and Kageboushi

### ISSUE THREAD

**Issue by JuuzaAmakusa** [07th-mod/higurashi-console-arcs#54]
Chisato is standing above the textbox in Someutsushi. I'm not sure when exactly this happens, but should be within first 30 minutes of the chapter.

![20191205220540_1](https://user-images.githubusercontent.com/58593391/70319230-26351d00-1865-11ea-9297-b3fa00662661.jpg)

Two Natsumis in Kageboushi. Happens immediately after POV switch from Akasaka at the beginning of the chapter.

![20191206201508_1](https://user-images.githubusercontent.com/58593391/70319225-20d7d280-1865-11ea-972e-fdeaa3319444.jpg)

**Comment by JuuzaAmakusa** [comment]
This is a separate issue from one in the subject, but I encountered it immediately afterwards, so...

![20191206203123_1](https://user-images.githubusercontent.com/58593391/70320214-7e6d1e80-1867-11ea-959f-9c0ed7ec0b26.jpg)

"Bishōjo game" doesn't mean "girly game", it means game where you date bishojos, should be left as is or translated as "dating sim"

**Comment by DoctorDiablo** [comment]
The extra Natsumi sprite is a random thing that can happen in all the arcs, and we've been trying to fix it for a while now.  But the other two were easy fixes so I just pushed fixes for both.

Thanks for pointing these out.  I'll leave this open in case you find anything else.

**Comment by JuuzaAmakusa** [comment]
I don't think I can find much, I'm a filthy speedreader and usually ignore bugs that aren't funny or crashing the game.

![20191004113731_1](https://user-images.githubusercontent.com/58593391/70382818-7c10de80-19a5-11ea-91d5-9f21242f9f50.jpg)

There's this from Himatsubushi, not sure if it was already fixed. Took a screenshot when I was reading it two months ago because I thought it was funny to have silly typo not once but twice during an emotional scene.

![20191208102720_1](https://user-images.githubusercontent.com/58593391/70382826-c003e380-19a5-11ea-84ca-9b210332b064.jpg)

And this is during chapter 12 of Kageboushi, typo in "datective".

**Comment by DoctorDiablo** [comment]
Fixed in the latest release
