### ISSUE TITLE
Kotohogushi Ambiguous Translation

### ISSUE THREAD

**Issue by hanss314** [07th-mod/higurashi-console-arcs#572]
It is ambiguous to whether the english should be interpreted as `my name means "the feathers of the bird wings in this land."` or `my name means "the feathers of the bird wings" in this land.`, although from what I understand the latter is intended.

Also, forgive my poor japanese, but from what I understand, would this line be better translated as "the wings or feathers of birds"?

https://github.com/07th-mod/higurashi-console-arcs/blob/master/Update/koto_003.txt#L1837

**Comment by DoctorDiablo** [comment]
I went ahead and pushed fix for this. I went with "And by the way, my name means the feathers or wings of birds, as you'd say in this land."

Thanks for pointing it out, sorry for the slow response.
