### ISSUE TITLE
Typo in  Someutsushi-hen

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#581]
![TYPO](https://user-images.githubusercontent.com/107649321/174439777-1b19a75d-7e5b-4480-9ed6-72a3c7d91394.JPG)

I think this is a typo in the all cast review session. Isnt it suppose to be Hinamizawa. Its spelt Himanizawa

**Comment by arbok3135** [comment]
![d](https://user-images.githubusercontent.com/107649321/174452818-8d8ffcfa-26ef-4765-901f-7a635095d3b2.JPG)
Idk if this counts as a typo but no space

**Comment by DoctorDiablo** [comment]
Fixed in this commit https://github.com/07th-mod/higurashi-console-arcs/commit/74a4b583c55fdd214cfa02395a8c784367a9f8cf
