### ISSUE TITLE
7 Instances of Text off screen in Kageboushi 

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#583]
![6](https://user-images.githubusercontent.com/107649321/174449374-0a0d3052-04c9-4250-aeb4-d9429abfb5cd.JPG)

I Dont know if thats intentional. or not. Just never seen that happen before. Sorry for loads of reports fix when u want im just pointing it out incase you guys werent aware of it

**Comment by arbok3135** [comment]
![65](https://user-images.githubusercontent.com/107649321/174452783-1ae62c45-efa1-4e27-a73d-864eba8dffc9.JPG)

**Comment by arbok3135** [comment]
![g](https://user-images.githubusercontent.com/107649321/174456048-244b3404-0541-4085-b7d5-c8c26f9b8c9a.JPG)
text cut off

**Comment by arbok3135** [comment]
![1](https://user-images.githubusercontent.com/107649321/174473283-d3e8ab82-10ea-4c0d-af35-01aeafdd1f62.JPG)

**Comment by arbok3135** [comment]
![uuu](https://user-images.githubusercontent.com/107649321/174482976-a1593f74-20b8-4396-b97f-01e437beb7a6.JPG)

**Comment by arbok3135** [comment]
![N](https://user-images.githubusercontent.com/107649321/174497087-53d09767-f24c-45dc-bcf7-fd0761451bcb.JPG)

**Comment by arbok3135** [comment]
![e](https://user-images.githubusercontent.com/107649321/174499543-ad43c77f-cb61-4e02-989e-1e94e9a4610e.JPG)
da epic fight scene with natsumi and chisato

**Comment by DoctorDiablo** [comment]
Resolved by this change https://github.com/07th-mod/higurashi-console-arcs/commit/193d7f1ba735de6b932fb7e4dbe5148c910c6a80
