### ISSUE TITLE
Kageboushi glitch Script bug

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#584]
![y](https://user-images.githubusercontent.com/107649321/174450653-55c33f4b-388c-4617-8f77-9e42a937d8f6.JPG)
I Dont know if this  <I> thing is intentioanl or not but i dont think it is

**Comment by DoctorDiablo** [comment]
Fixed in this commit https://github.com/07th-mod/higurashi-console-arcs/commit/74a4b583c55fdd214cfa02395a8c784367a9f8cf
