### ISSUE TITLE
3 Kageboushi typos

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#585]
![423](https://user-images.githubusercontent.com/107649321/174451483-231f99e9-9733-4d90-b10a-b77f578fb460.JPG)
meant to say concerned

**Comment by DoctorDiablo** [comment]
Seems like you're finding a bunch of these, so maybe it would be better to post any more you find as comments here in this issue. That way they're all together and it's a little easier to keep track of.

Thanks again for pointing stuff out!

**Comment by arbok3135** [comment]
Sorry about this. Im just trying to help lol i will combine them now.

**Comment by arbok3135** [comment]
![r](https://user-images.githubusercontent.com/107649321/174453033-455d7adb-c0e6-457f-945e-a4479feb0bb4.JPG)

**Comment by arbok3135** [comment]
![z](https://user-images.githubusercontent.com/107649321/174480527-db34a6c8-f385-4c7e-ba49-f2d17e0a8b10.JPG)
meant to say something

**Comment by DoctorDiablo** [comment]
Fixed in this commit https://github.com/07th-mod/higurashi-console-arcs/commit/74a4b583c55fdd214cfa02395a8c784367a9f8cf
