### ISSUE TITLE
Text Going off Screen in Yoigoshi

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#587]
![t](https://user-images.githubusercontent.com/107649321/174661828-911d2c24-cb51-49dd-83e5-8647015eeb67.JPG)

ignore  the 2nd screen i accidently took a picture of both monitors

**Comment by DoctorDiablo** [comment]
Resolved by this change https://github.com/07th-mod/higurashi-console-arcs/commit/193d7f1ba735de6b932fb7e4dbe5148c910c6a80
