### ISSUE TITLE
Tokihogushi-hen 2 Times  Text going off Screen 

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#588]
![MMM](https://user-images.githubusercontent.com/107649321/174676432-77fd59c1-304a-4700-8ff5-872eebdd2436.JPG)

**Comment by arbok3135** [comment]
![nnnnn](https://user-images.githubusercontent.com/107649321/174827076-4c9c13b1-e5b1-4d33-bff6-f8398ad4f0df.JPG)

**Comment by DoctorDiablo** [comment]
Resolved by this change https://github.com/07th-mod/higurashi-console-arcs/commit/193d7f1ba735de6b932fb7e4dbe5148c910c6a80
