### ISSUE TITLE
1 Connecting Fragment typo 

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#589]
![image](https://user-images.githubusercontent.com/107649321/174873499-38fc11e2-f0d8-4dbd-997c-de84d8f14f59.png)
Been twice??

**Comment by DoctorDiablo** [comment]
Fixed in this commit https://github.com/07th-mod/higurashi-console-arcs/commit/74a4b583c55fdd214cfa02395a8c784367a9f8cf
