### ISSUE TITLE
Miotsukushi Ura 4 Times Text going off Screen 

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#590]
![23](https://user-images.githubusercontent.com/107649321/175039005-4c7dcc4e-3301-4445-ba4a-5c8573fb5bf7.JPG)
![h](https://user-images.githubusercontent.com/107649321/175039019-ae447594-ac57-48e8-a79b-d3e8e15260d0.JPG)

**Comment by arbok3135** [comment]
![t](https://user-images.githubusercontent.com/107649321/175645920-4a2dddcb-c606-47fa-827e-51fc8faa10aa.JPG)

**Comment by arbok3135** [comment]
![image](https://user-images.githubusercontent.com/107649321/175668148-6e92def0-aca0-4fcd-9d09-307d7d2df481.png)

**Comment by DoctorDiablo** [comment]
Resolved by this change https://github.com/07th-mod/higurashi-console-arcs/commit/193d7f1ba735de6b932fb7e4dbe5148c910c6a80
