### ISSUE TITLE
3 Typos in Miotsukushi Ura 

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#591]
![image](https://user-images.githubusercontent.com/107649321/175125639-4a3008e3-a55a-4076-bd2f-ceed01758d30.png)
you? not your?

**Comment by arbok3135** [comment]
![image](https://user-images.githubusercontent.com/107649321/175352381-c3255424-6dc5-4fa5-8ef8-3667f4345676.png)
Isn't there suppose to be a space?

**Comment by arbok3135** [comment]
![image](https://user-images.githubusercontent.com/107649321/175644438-20f1f8e2-e5d4-4e86-bc00-7eccd2a1dc5a.png)
that sentenace doesnt make sense to me just putting it here incase it is a typo and the was key? idk i f that makes sense

**Comment by DoctorDiablo** [comment]
Fixed in this commit https://github.com/07th-mod/higurashi-console-arcs/commit/74a4b583c55fdd214cfa02395a8c784367a9f8cf
