### ISSUE TITLE
Typo in Kotohogushi

### ISSUE THREAD

**Issue by arbok3135** [07th-mod/higurashi-console-arcs#592]
![image](https://user-images.githubusercontent.com/107649321/176507993-22660aa8-76b9-4574-9dc3-3733f08d21ff.png)

**Comment by DoctorDiablo** [comment]
Fixed in this commit https://github.com/07th-mod/higurashi-console-arcs/commit/74a4b583c55fdd214cfa02395a8c784367a9f8cf
