### ISSUE TITLE
Typos in Tsukiotoshi

### ISSUE THREAD

**Issue by huythekirby** [07th-mod/higurashi-console-arcs#60]
I found some typos while reading Tsukiotoshi:
![image](https://user-images.githubusercontent.com/60413415/73318290-295de100-41f6-11ea-82d0-f4abbd6aa187.png)
-> Should be "and" instead of "an"
![image](https://user-images.githubusercontent.com/60413415/73318312-3b3f8400-41f6-11ea-816e-f41209b68cfd.png)
-> "too well" instead of "to well"
![image](https://user-images.githubusercontent.com/60413415/73318342-527e7180-41f6-11ea-84ca-7d35f863263a.png)
-> "the atmosphere of" instead of "the atmosphere if"

**Comment by DoctorDiablo** [comment]
Just pushed a fix for these.  Thanks for pointing these out.  Feel free to post here if you find any more.
