### ISSUE TITLE
More robust choice implementation

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#64]
The current choice implementation works, but some users would like to have a way of knowing which choices will lead to bad endings (without relying on an out of game flowchart), and some users don't like having choices at all.

Proposed solution: At the start of any arc that contains choices, ask the user which of three choice modes they'd like to use
- Do not prompt choices at all. Just proceed down the path to the good ending.
- Prompt choices normally.
- Prompt choices, with correct and incorrect answers highlighted.

Store that result in a global, then check that value before prompting any choices.  If it's 0, skip the choice, if 1 do as we do today, and if 2 use a variant of the 2choices.png image with check marks on right answers and Xes on wrong ones.

**Comment by DoctorDiablo** [comment]
I've got a plan that seems to work, pending some more testing.  It just requires a new global be created to store the choices mode. (using GArtStyle as a placeholder atm)

Call this guy at the start of the arc [&choicesdialog.txt](https://github.com/07th-mod/higurashi-console-arcs/files/4284469/choicesdialog.txt)

And do this any time you need to prompt a choice: 
![image](https://user-images.githubusercontent.com/20390474/75834620-8109e200-5d8a-11ea-98e8-fdcae7be6f58.png)

**Comment by DoctorDiablo** [comment]
@tellowkrinkle @idealpersona Can one of you create a new global for me?  You can call it GChoiceMode, and if it matters it's an integer in the range 0-2.  It should be merged into all arcs because I'm planning to implement this in the arcs in the main series we added choices to, as well.

I did some testing on this, and I'm pretty satisfied it'll work.  Loading saves before/after the choice didn't break anything, and it worked the same whether you got there normally or via chapter jump.

**Comment by tellowkrinkle** [comment]
Should be in, try the latest DLL?

**Comment by DoctorDiablo** [comment]
In latest release.
