### ISSUE TITLE
Someutsushi poem

### ISSUE THREAD

**Issue by Kamil689** [07th-mod/higurashi-console-arcs#7]
It seems that Someutsushi has a poem as shown in [this](https://youtu.be/MmFfMfauJfA?t=3m6s) video. I've found it in the PS3 graphics rip (some_fre.png):
![some_fre](https://user-images.githubusercontent.com/22866160/28247210-22cb4bb0-6a2c-11e7-8742-bf3ba4040f21.png)

Do you plan to translate and implement it into the mod?

**Comment by DoctorDiablo** [comment]
Thanks for pointing that out.  I'll include it in the next release.  Here's a quick translation:

![some_fre](https://user-images.githubusercontent.com/20390474/28249139-37ade60e-6a1e-11e7-9b33-74783a6eab99.png)

**Comment by DoctorDiablo** [comment]
Fixed in the v1.4 release
