### ISSUE TITLE
Taraimawashi Title Error

### ISSUE THREAD

**Issue by Tymaeus** [07th-mod/higurashi-console-arcs#70]
Taraimawashi title image has "Stain Following" written as its translation. This is Someutsushi's translation.  "Taraimawashi" literally means "handing the problem off to someone else to evade responsibility". Perhaps "Responsibility Dodging" would be an effective translation.

**Comment by DoctorDiablo** [comment]
Looks like a copy paste error.  My original translation for it was "Idly Spinning" which kind of conveys the idiom's idea of moving without accomplishing anything, while also literally conveying mawasu.
